### ISSUE TITLE
Support for ingredients that take damage

### ISSUE THREAD

**Issue by 7eggert** [CyclopsMC/IntegratedCrafting#101]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Gregtech uses tools as ingredients, these tools take damage when crafting. These tools should be supported.

I imagine if the tools are counted as $DAMAGE items, it would be easy to implement. New tools could automatically be crafted.

Otherwise I'd be willing to risk that a craft job halts when the tools are gone. Just ignore the damage. This would also fix an issue with the terminals when pasting recipes from JEI.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
This is already supported by marking recipes are reusable:

> If you want to configure recipes that do not fully consume input items, but for example only consume part of the durability of that item, you may configure those recipe ingredients as reusable. This can be done during recipe Variable Card creation by shift-clicking on an input slot inside the Logic Programmer and enabling the Reusable checkbox.

**Comment by 7eggert** [comment]
Tested again, it does not work. It does not even work with undamaged gregtech tools

I think this might turn out to be a bug then?

Minecraft 1.20.1 / Forge 47.2.19 / GDLauncher

list of mods:
AE2-Things-1.2.1.jar
AdFinders-1.20.1-9.1.1.0-build.0270.jar
AdvancedPeripherals-1.20.1-0.7.35b.jar
Bookshelf-Forge-1.20.1-20.1.8.jar
BotanyPots-Forge-1.20.1-13.0.18.jar
BuildingWands-mc1.20.1-2.6.8-release-forge.jar
CommonCapabilities-1.20.1-2.9.1.jar
CyclopsCore-1.20.1-1.18.14.jar
DarkUtilities-Forge-1.20.1-17.0.3.jar
DrawersTooltip-1.20.1-forge-8.0.0.jar
EnderIO-1.20.1-6.0.23-alpha.jar
FastLeafDecay-31.jar
FluxNetworks-1.20.1-7.2.0.14.jar
ForgeEndertech-1.20.1-11.1.0.1-build.0289.jar
FpsReducer2-forge-1.20-2.5.jar
IntegratedCrafting-1.20.1-1.1.7.jar
IntegratedDynamics-1.20.1-1.20.4.jar
IntegratedTerminals-1.20.1-1.4.12.jar
IntegratedTunnels-1.20.1-1.8.24.jar
Jade-1.20.1-forge-11.7.1.jar
JadeAddons-1.20.1-forge-5.2.2.jar
LibX-1.20.1-5.0.12.jar
Mekanism-1.20.1-10.4.5.19.jar
Mekanism-MoreSolarPanels-1.20.1-1.5.8.jar
MekanismGenerators-1.20.1-10.4.5.19.jar
MekanismWeapons-1.20.1-1.3.jar
MoreMekanismProcessing-1.20.1-4.0.jar
MouseTweaks-forge-mc1.20-2.25.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
PortableCraftingTable-1.20.1-3.2.2-[FORGE].jar
Powah-5.0.4.jar
Shrink-1.20.1-1.4.5.jar
SimplyTools-1.20.1-2.0.5.jar
ThermalExtra-3.0.8-1.20.1.jar
WitherSkullOres-[1.20.1]-1.0.jar
XaerosWorldMap_1.37.2_Forge_1.20.jar
Xaeros_Minimap_23.9.3_Forge_1.20.jar
[1.20][Quilt]TorchBowMod_v1.0.jar
ae2qolrecipes-neoforge-1.20.1-1.1.1.jar
appleskin-forge-mc1.20.1-2.5.1.jar
appliedenergistics2-forge-15.0.19.jar
architectury-9.1.12-forge.jar
badpackets-forge-0.4.3.jar
balancedflight-1.20.1_v2.2.0.jar
balm-forge-1.20.1-7.2.1.jar
botarium-forge-1.20.1-2.2.3.jar
buildinggadgets2-1.0.6.jar
carryon-forge-1.20.1-2.1.2.7.jar
cc-tweaked-1.20.1-forge-1.109.3.jar
cccbridge-mc1.20.1-forge-1.6.3.jar
chunkloaders-1.2.8a-forge-mc1.20.1.jar
cloth-config-11.1.118-forge.jar
cofh_core-1.20.1-11.0.0.51.jar
collective-1.20.1-7.30.jar
corpse-1.20.1-1.0.9.jar
cosmeticarmorreworked-1.20.1-v1a.jar
create-1.20.1-0.5.1.f.jar
create-new-age-forge-1.20.1-1.1.1.jar
create-stuff-additions1.20.1_v2.0.4a.jar
create_recycle_1.0.2_forge_1.20.1.jar
createoreexcavation-1.20-1.4.2.jar
curios-forge-5.4.7+1.20.1.jar
densemekanism-1.20.1-1.1.0.jar
disenchanting_table-merged-1.20.1-2.0.0.jar
doubledoors-1.20.1-5.2.jar
effortlessbuilding-1.20.1-3.7-all.jar
endercrop-1.20.1-1.7.0.jar
extremesoundmuffler-3.41-forge-1.20.1.jar
geckolib-neoforge-1.20.1-4.3.1.jar
gtceu-forge-1.20.1-1.0.20.b.jar
inventoryessentials-forge-1.20.1-8.2.1.jar
inventorysorter-1.20.1-23.0.1.jar
invhud.forge.1.20.1-3.4.18.jar
itemcollectors-1.1.9-forge-mc1.20.jar
jei-1.20.1-forge-15.2.0.27.jar
laserio-1.6.7.jar
letmedespawn-forge-1.20.x-1.2.0.jar
mcjtylib-1.20-8.0.3.jar
megacells-forge-2.2.9-1.20.1.jar
mob_grinding_utils-1.20.1-1.0.3.jar
nocube's_create_compact_exp_1.0.3_forge_1.20.1.jar
rftoolsbase-1.20-5.0.2.jar
rftoolsbuilder-1.20-6.0.3.jar
rftoolsdim-1.20-11.0.5.jar
rftoolspower-1.20-6.0.1.jar
rftoolsstorage-1.20-5.0.2.jar
rftoolsutility-1.20-6.0.5.jar
rightclickharvest-quilt-4.1.3+1.20.4.jar
simplemagnets-1.1.10-forge-mc1.20.jar
sleeping_bags-1.20.1-1.0.3.jar
spyglass_improvements-1.4+mc1.20+forge.jar
storagedrawers-1.20.1-12.0.2.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.16-forge-mc1.20.1.jar
tesseract-1.0.35a-forge-mc1.20.1.jar
thermal_dynamics-1.20.1-11.0.0.21.jar
thermal_expansion-1.20.1-11.0.0.27.jar
thermal_foundation-1.20.1-11.0.2.64.jar
torchmaster-20.1.5.jar
trashcans-1.0.18b-forge-mc1.20.jar
trashslot-forge-1.20-15.1.0.jar
waystones-forge-1.20-14.1.3.jar
wirelesschargers-1.0.9-forge-mc1.20.jar
wits-1.1.0+1.20.1-forge.jar
worldedit-mod-7.2.15.jar
xnet-1.20-6.0.2.jar
xnetgases-1.20.1-5.0.0.jar

crafting card
![crafting card](https://github.com/CyclopsMC/IntegratedCrafting/assets/924567/b0ad4326-1be2-4a74-8767-a4f312af5617)

crafting tree (always the same)
![crafting tree (always the same)](https://github.com/CyclopsMC/IntegratedCrafting/assets/924567/40e2a33c-d85c-4ec9-b253-c4f4022bcf32)

JEI R key crafting
![JEI R key crafting](https://github.com/CyclopsMC/IntegratedCrafting/assets/924567/a2bb7d87-cb1f-4883-af7a-2d772d303dd8)

JEI R key crafting result (items moved but not wrench)
![JEI R key crafting result (items moved but not wrench)](https://github.com/CyclopsMC/IntegratedCrafting/assets/924567/6b2773c3-1119-49c7-be6c-f1d4b22eb923)

put in a non-defective wrench (still fails)
![put in a non-defective wrench](https://github.com/CyclopsMC/IntegratedCrafting/assets/924567/9c7531f0-896e-4457-86ce-4b926605561e)

Not even an aluminum wrench works for crafting
![Not even an aluminum wrench works](https://github.com/CyclopsMC/IntegratedCrafting/assets/924567/93d0a1a1-7518-4f26-8373-907b1debe30f)

**Comment by rubensworks** [comment]
Hmm, weird that it doesn't even work even when you have a non-damaged item available.

Can you try an exact item match? So without the item tag variants?

Could you try installing EvilCraft in your pack to see if the shears+sapling->dead_bush recipe works? That one definitely used to work. So if that also breaks on your end, then it might be a pack issue (possibly caused by another mod).

**Comment by 7eggert** [comment]
I get as many bushes as the shears can provide, more if I throw in a second shears.

Re-using the damaged Gregtech wrench does work if I specify a specific one (thanks), but I need as many wrenches as crafting jobs. Edit: Also only wrenches with the same damage are considered, if there is one damaged one not, only one  is counted, if two are damaged by the same amount, both are found.

I suspect Greg re-invents the damage system.

**Comment by rubensworks** [comment]
> I suspect Greg re-invents the damage system.

This is a possibility indeed.

Could you open an issue at the Gregtech issue tracker about this?

Have you checked with AE2/RS by any chance to see if they experience the same problem?
