### ISSUE TITLE
Gregtech tools not detected in recipes that use a tool tag

### ISSUE THREAD

**Issue by Rosethorns** [CyclopsMC/IntegratedCrafting#102]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When a crafting recipe using **item tag variants** requires a GTCEU modern tool, the recipe is valid but cannot find the ingredient even if present. It does not matter if the recipe is set to reusable or not.

However if you provide the crafter with any other valid **non**-gregtech tool, the ingredient is found correctly.

When the same recipe uses a gregtech tool without **item tag variants** it functions as expected.

#### Steps to reproduce the problem:

1. Setup a simple Storage Monitor crafting system.
2. Create a recipe that requires a gregtech modern tool
3. ensure that it is set to **item tag variants**
4. Attempt to craft the item from the monitor

#### Expected behaviour:

For the crafting interface to find the valid tagged tool and for the crafting job to be complete

____

#### Versions:

- This mod: 1.1.7
- Minecraft: 1.20.1
- NeoForge: 47.1.83
- Gregtech Modern: 1.1.1.a

#### Log file:

None produced.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Since it only fails with GT, I suspect this is a problem on GT's end.
Sounds similar to #101, which is suspected to be a GT-specific issue as well.

Could you report this to GT's issue tracker?
Happy to make changes here if that would be needed.

**Comment by Rosethorns** [comment]
As the greg recipes work in hand, in crafting table, and in the back ported auto crafting table, it was determined to be a specific foible with how ID Crafting might be retrieving tags.
