### ISSUE TITLE
Invalid Chars in Tag Within Recipe Can Be Saved To Variable

### ISSUE THREAD

**Issue by EddwardR** [CyclopsMC/IntegratedCrafting#103]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When inputting a recipe in Programmer, using the format of `#namespace:item` instead of `namespace:item` within "Item tag variants" option can still be written to variable card if one is placed in output slot.

#### Steps to reproduce the problem:

1. New Recipe in Logic Programmer
2. Input a valid recipe that uses tags (sticks recipe is a good candidate) via JEI, REI or EMI
3. Modify input tag on one of planks to contain an illegal character, like `#`
4. Click variable card into output slot. This should result in a crash

#### Expected behaviour:

Blocking or otherwise disallowing a variable card to be written at all. An option would be blocking the output slot with the advanced config UI.
____

#### Versions:

- This mod: 1.1.7
- Minecraft: 1.20.1
- NeoForge: 47.1.96

#### Log file:
https://mclo.gs/HsROiiC

**Comment by rubensworks** [comment]
Thanks for reporting!
