### ISSUE TITLE
Nullpointer crash

### ISSUE THREAD

**Issue by MCBEModder2020** [CyclopsMC/IntegratedCrafting#104]
#### Issue type:

- :bug: Crash 

____

#### Short description:
editing network causes crash

#### Steps to reproduce the problem:
make crafting job
edit network

#### Expected behaviour:
it doesent crash

____

#### Versions:

- This mod: latest
- Minecraft: 1201
- Forge: idk

#### Log file:

java.lang.NullPointerException: Cannot invoke "org.cyclops.integratedcrafting.api.crafting.CraftingJob.getAmount()" because "craftingJob" is null

**Comment by rubensworks** [comment]
Could you share the full crashlog and full version details?

**Comment by rubensworks** [comment]
@TheKidThatCodes Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.

**Comment by MCBEModder2020** [comment]
im sorry about breaking your automation, i dont know how to fix it now
this should only need to be tested and then add a null check somewhere right? i currently don't have a pack with id and ic to get you a crash log, and as of writing this my pc is still in it's 15 min boot cycle
