### ISSUE TITLE
Crafting Jobs hanging when outsourced to an external machine

### ISSUE THREAD

**Issue by UnseenFaith** [CyclopsMC/IntegratedCrafting#105]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When initiating a crafting job, the crafting job gets hung up on a recipe that is outsourced to an external machine. The recipe gets stuck on waiting on things to be crafted.

The recipe I was testing it on is a Sophisticated Storage Netherite Stack Upgrade. The recipe requires a netherite block and multiple netherite ingots. The crafting would get stuck on crafting the netherite ingots for both the upgrade itself and the blocks for the upgrade when the recipe was connected to a Thermal Dynamics Induction Smelter. However, when moving it over to a regular crafting bench and Vanilla Minecraft recipe, the craft finished properly, and I was also able to initiate another one and it worked flawlessly. 

There was also a point where it got hung up on the craft, and upon breaking almost every single crafting interface, cable, terminal, and importers, and replacing them, the crafting was able to finish where it had left off when started up again, but on the next craft it got hung up in the same exact spot.

I am unsure if it's related to the Thermal Expansion machine itself or if it's just any external machine, I don't currently have anything else made to test the other recipes in the modpack.

It's worth mentioning that I am playing on ATM9, and there have been a lot of buggy interactions with ID and some of the mods in the modpack.

#### Steps to reproduce the problem:

1. Create all the recipes you need for the upgrade
2. Create a Thermal Expansion Induction Smelter and use it to make the netherite over the Vanilla recipe
3. Initiate a craft once everything is setup
4. It will hang upon finishing the diamond upgrades and get stuck at the netherite ones

#### Expected behaviour:

The induction smelter should fire up and start smelting the netherite for the craft, instead of getting hung up on the crafting job.
____

#### Versions:

- This mod: 1.20.1-1.1.7
- Minecraft: 1.20.1
- Forge: 47.2.20

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Can you check if `craftingPlannerEnableMultithreading` in the Terminals config is definitely set to `false`?

Are you experiencing any differences when disabling/enabling blocking mode?

**Comment by UnseenFaith** [comment]
The option is definitely set to false.

There was no difference when enabling or disabling blocking mode. I tried every combination on each of the crafters I had.

**Comment by rubensworks** [comment]
Could you share a screenshot of the crafting terminal that shows where it hangs?
Or if possible, a video about the setup and demonstration of the problem would be even better.

**Comment by UnseenFaith** [comment]
Sure thing, I will update this comment with a picture of it, I wanted to mention that I went into a minimum reproduction of the mods working together and they seem to work outside of the ATM environment. I figured it would, as a lot of the other issues that  ATM9 have not been reproducible outside of itself. So it's likely a mod compatibility issue.

**Comment by rubensworks** [comment]
I see, that's interesting.
Did you minimal reproduction include Thermal Dynamics? Or was it purely using vanilla machines?

**Comment by UnseenFaith** [comment]
It was with Thermal Dynamics
Edit: Also no config changes from ATM at all, just purely throwing the mods together with the same versions as ATM9

**Comment by rubensworks** [comment]
Hmm, that's going to be an annoying one to debug then 😅 

Could you copy over all ID-related configs from your ATM instance to your minimal instance? Maybe ATM changed some configs that somehow broke things.
(If that's not the problem, I don't have a clear idea atm on where the problem might lie)

**Comment by UnseenFaith** [comment]
Here's what the crafting planner looks like. I took out the recipe for the vanilla crafting, inserted the one for the induction smelter. It did one complete craft of one item. Then upon initiating the second craft of that item, it gets hung up and looks like this.

![image](https://github.com/CyclopsMC/IntegratedCrafting/assets/1832323/a86496fd-b063-4d9a-b751-a65cabd53858)

Yeah, I can copy over the configs and check that as well. I also didn't actually check if it's a problem with the second craft on the minimal reproduction. It does indeed work on the first craft, just not subsequent crafts. I'll try that as well before then.

Edit: It seems like any subsequent crafts are fine on the non ATM environment, I'll copy over the configs now

Edit 2: Upon copying over the configs from the ATM9 instance over to the minimal reproduction, it now hangs and doesn't work at all, and produces the same crafting planner output.

![image](https://github.com/CyclopsMC/IntegratedCrafting/assets/1832323/939831f1-273b-4002-b7ba-4766970faae5)

Edit 3: I restored the default configs to confirm if it was the configs and noticed that the craft wouldn't start/finish until I broke the crafting interface and replaced it. Unsure if that means anything, I thought maybe the network might need a block update to get updated config values or something similar, that seems silly though.

Edit 4: I am also noticing that in the original minimal reproduction world that the crafting is generally just broken in general, even with replacing the crafting interface, it ends up breaking after the next craft. This was after moving the ATM configs over, and then removing them and regenerating defaults. I made a new fresh world with the original default configs and it works as intended again.

Edit 5: This'll be my last edit for the night, sorry for so many, wanted to document what I observed. I noticed the second world I created also eventually had the same issue where it just gets hung up, so the issue may be isolated from ATM. I created another world from scratch and did the same exact setup and have yet to experience the issue, so I'm really unsure what the underlying cause is, or any general direction as to what it could possibly be

**Comment by UnseenFaith** [comment]
Upon opening up the minimal modpack and loading into the third world I created last night and attempting to craft the recipe, it now hangs in the exact spot.

**Comment by UnseenFaith** [comment]
When messing around with the Network reader, I noticed that the Active Crafting Jobs Aspect (and by extension, the Crafting Ingredients Aspect) is still showing a Netherite Ingot being crafted, but the crafting planner shows no mention of any crafting jobs at all. That appears to be the case for both the ATM version and the minimal reproduction version

![image](https://github.com/CyclopsMC/IntegratedCrafting/assets/1832323/68a9ccb4-7f63-492c-9903-69ece235ea8f)
![image](https://github.com/CyclopsMC/IntegratedCrafting/assets/1832323/722f7309-a4a3-4b55-810c-0976853d405f)

**Comment by rubensworks** [comment]
@UnseenFaith Thanks for the additional debugging!
So just so I understand your previous messages correctly; with the ATM configs the problem occurs, while it doesn't with the default configs?
If so, could you share with me both sets of configs so I can diff them? (or if you already see some important differences, feel free to play with them)

**Comment by UnseenFaith** [comment]
I think the problem occurs even without the ATM configs, so I think the problem is isolated from ATM. The third world I created last night before going to bed, ended up having the same issue when I woke up and tried it today, and that's with complete default configs

**Comment by rubensworks** [comment]
Ok, I see.
Would it be possible to create a video that shows every step to reproduce the problem?
Or, what would make my debugging effort easier, would be a way to reproduce the problem with just vanilla machines, as this would allow me to debug the problem easily within a development environment.

**Comment by UnseenFaith** [comment]
I am unsure if it actually happens with only Vanilla machines, but I could try. I'm not sure how much of a reproducible product I can provide. It's really random. I created the third world last night, and it was working fine, and then fast forward to waking up and trying it, it starts getting hung up on the recipe. I did notice however in the last screenshot there seems to be a rogue recipe left in the system

**Comment by rubensworks** [comment]
> It's really random

Yeah, these kinds of bugs are the worst 😅 

Well, if you find out anything more, be sure to let me know.
I'll also do some thinking in the meantime on how we could debug this further.

**Comment by UnseenFaith** [comment]
Alright, if I can come up with anything else I'll be sure to add it to this thread. If I had to take a shot in the dark I think it has something to do with the interaction between crafting interface and an outside machine. In the screenshot, there that the rogue recipe, and I did notice upon breaking that specific interface that crafts that item that the recipe ends up being removed correctly.
