### ISSUE TITLE
Carpenter compat (from forestry) is totally broken

### ISSUE THREAD

**Issue by Wizzerinus** [CyclopsMC/IntegratedCrafting#108]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Autocrafting in Carpenter does not work if Forestry compat is enabled in Common Capabilities settings (which is the default).

Part 1. Carpenter recipes cannot be encoded, even though they fit under the 9 input + 1 fluid -> 3 output (actually 1) and 1 fluid output (actually 0).

![image](https://github.com/user-attachments/assets/4b9c06dd-acb8-4071-9c47-ff3d37dbb6e5)

Part 2. Encoding a carpenter recipe manually makes the Crafting Interface not recognize it:

![image](https://github.com/user-attachments/assets/d417996f-e4cb-4624-a24b-69255e8b3cb6)

![image](https://github.com/user-attachments/assets/ee6bfc87-1346-4d44-afd5-0225d9c8c88f)

This gets fixed if Forestry compat is disabled in settings of Common Capabilities.

#### Steps to reproduce the problem:

1. Put a crafting interface on Carpenter
2. Encode a Carpenter recipe
3. Put the recipe into the crafting interface
4. It says "this machine can't do this recipe" or something like that

#### Expected behaviour:

I can autocraft with carpenter like any normal machine
____

#### Versions:

- This mod: 1.0.10
- Minecraft: 1.12.2
- Forge: 14.23.5.2860
- Forestry: 5.8.2.422

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm sorry, buy 1.12 is not supported anymore.

**Comment by Wizzerinus** [comment]
the part 3 was a mistake on my part (wrong NBT encoding I think). parts 1 and 2 still exist

**Comment by Wizzerinus** [comment]
oop I see
