### ISSUE TITLE
Auto-crafting of missing ingredients

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedCrafting#109]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

How about to implement auto-crafting missing ingredients in the crafting Grid? 

In ID currently, if in the complex receipt some ingredients missed, then they are marked with red tint, and I need to search first of them and start craft and return to receipt again and see what if you need other item and search again... It would be very convenient to get some auto-crafting possibilities here, if crafting interface exists for missed ingredients.

The competitor (Refined Storage) has such feature. I do not ask to do the absolutely the same, because their implementation is not the best possible, but at least it works somehow and sometimes (and sometimes glitches). RS marked missed ingredients with red tint in the grid, but if some missed item may be auto-crafted, then tint is bluish. If press Shift+Click, the auto-crafting is started. And if you open grid again (here is not convenient moment, because you need to search receipt again) you can see as bluish items become not-tinted and you can make normal click to craft final item.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Having something like this could be useful indeed.

**Comment by rhullah** [comment]
If I'm reading this issue correctly, I think this was resolved by this other [issue/pr](https://github.com/CyclopsMC/IntegratedTerminals/issues/127).

**Comment by rubensworks** [comment]
Aha, correct!

**Comment by uhloin** [comment]
Yes, it works, thank you. Is there some option to not reopen receipt after ctrl-click?
