### ISSUE TITLE
Recipes with "too many" ingredients fail to be crafted via terminal

### ISSUE THREAD

**Issue by MrDj200** [CyclopsMC/IntegratedCrafting#110]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When you make a Recipe that has more ingredients than the Logic Programmer has slots, you can't request the recipe via terminal, but it is possible via Crafting Writer.

#### Steps to reproduce the problem:

1. Make a recipe with 10 misc. items (doesn't have to be an existing recipe)
2. Put a crafting interface on a chest/barrel and insert recipe
3. Make sure the items are available in the network
4. Try to order through a Storage Terminal
5. Restart game
6. Try ordering again

(Alternatively, I've attached the modpack including the world I've used for testing. The pack has been exported as a CurseForge pack, so it should be compatible with most launchers)
[Integrated Dynamic Testing.zip](https://github.com/user-attachments/files/16662881/Integrated.Dynamic.Testing.zip)

#### Expected behaviour:

I'd expect to be able to order my programmed recipe through the terminal
____

#### Versions:

- This mod: `1.1.7`

- Minecraft: `1.20.1`
- Mod loader version:  `Forge 47.3.0`

#### Log file:

N/A

#### Additional Info:
This issue has a discord conversation preceding it: [Messages on the CyclopsMC Discord](https://discord.com/channels/386052815128100865/386054223688630272/1275108511033852038)

When I initially made the test setup, it worked, however after a world reload the issue started happening. That's why I've added step 5 for the reproduction.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by battle00333** [comment]
Should mention that this is occuring with the "Recipe.with_io" operator.
Ingredients -> Ingredients -> Recipe

I can confirm that I am also running into this issue when having an ingredient as input with more than 10 unique items.

Incidentally if you make a new card of the same signature and place it in a crafting terminal, it will flash an X for a brief moment before being recognized as valid.
removing/adding a component also appears to trigger the card to be recognized as valid.
I'll also mention that there was an "Unknown Error" that preceded this a couple days ago but so far it cannot be reproduced.

**Comment by rubensworks** [comment]
The fact that it works with the Crafting Writer but not the Terminal is strange. But it also makes me suspect that this one shouldn't be too difficult to fix, since we have one functional code path.

**Comment by MrDj200** [comment]
The crafting writer also seems to have an issue with these kinds of recipes. 
The `Ignore storage contents` setting seems to be non functional for this.
It works fine on "normal" recipes
