### ISSUE TITLE
Curios for Portable Terminal in 1.21.1

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedCrafting#111]
#### Issue type:

- :bug: Bug 

____

#### Short description:

If I remember correctly, in 1.20.1 Portable Storage Terminal uses curios slots Back/Belt. 
But in 1.21.1 it hasn't such functionality. 
Also Curios API in 1.21 is discontinued, but there are unofficial descendants:
https://www.curseforge.com/minecraft/mc-mods/curios-continuation
https://www.curseforge.com/minecraft/mc-mods/adorned
Both of them work with other mods, but not with ID.

#### Versions:

- This mod: 1.1.11
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.68

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by uhloin** [comment]
Thank you very much for fix!
