### ISSUE TITLE
Cannot auto-craft an Energy Interface or Energy Battery with JEI-created recipes

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedCrafting#113]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Energy Battery cannot be auto-crafted or is not recognized properly by auto-craft system

#### Steps to reproduce the problem:

1. Create network with some chest, Storage Interface and Crafting Job Terminal
2. Connect Crafting Interface to Crafting Table
3. Use Logic Programmer to create a Card with recipe of Energy Battery
(I selected it from JEI using "uncharged" icon)
4. Try insert a Card to Crafting Interface - will get red "X" about "Receipt is not acceptable by the target"
5. Try "Disable Craft Check" in the Crafting Interface - red "X" changed to green "V"
6. Also create and insert a Card with recipe of Energy Interface
7. Put enough of materials to system, try auto-craft 4 x Energy Interface - Job Terminal shows the job is sticked on Energy Battery creation
8. Cancel all jobs
9. Look into Storage Terminal - can see that in fact Battery was crafted
10. Try auto-craft 4 x Energy Interface again - this time - success

____

#### Versions:

- This mod: 1.1.11
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.68

Possible related issue:
https://github.com/CyclopsMC/IntegratedCrafting/issues/68

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> I selected it from JEI using "uncharged" icon

Can you try manually creating the recipe (without JEI)?

**Comment by uhloin** [comment]
Yes, I tried it. In this case there is no bug, no red cross on the step 4, not need to set "Disable Craft Check" and auto-crafting works fine from first attempt.

JEI incompatibility?

**Comment by rubensworks** [comment]
Great, thanks for checking.
Then it must be caused by ID's JEI recipe transfer logic.

**Comment by rubensworks** [comment]
The `ignoreDataComponentsForEqualityFilters` value in the common capabilities must be changed to `cyclopscore:energy_storage`.
The new update will set this as default value, but existing configs may have to be changed manually.

**Comment by uhloin** [comment]
if I set ignoreDataComponentsForEqualityFilters = [cyclopscore:energy_storage]
then it is cleared after restart MC and reload game
