### ISSUE TITLE
Ars Nouveau cannot properly break cables (compatibility issue)

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedCrafting#114]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Ars Nouveau cannot properly break cables

#### Steps to reproduce the problem:

1. Install some Ars Nouveau version
2. Generate (in creative mode) a Novice Spell Book
3. Press default 'C' key to open book
4. Select glyphs "Touch" and "Break"
5. Put the book to hotbar, select it, try right click to some dirt - it breaks
6. Try right click to some cable - it DOES NOT break
7. Try right click by PICKAXE to some cable - it DOES break

#### Expected behaviour:

____

#### Versions:

- This mod: 1.1.11
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.68

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
You may want to report this to the Ars Nouveau issue tracker first.
It's likely that they are handling block breaks in a special way.

**Comment by uhloin** [comment]
OK, I will duplicate the bug to them
