### ISSUE TITLE
Jade cannot properly show cables (compatibility issue)

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedCrafting#115]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Jade cannot properly show cables

#### Steps to reproduce the problem:

1. Install some version of Jade
2. Make network with cables, 
3. Connect Storage Terminal, Item Importer to cables
4. Hover with mouse over cable - Jade shows correct text "Logic Cable"
5. Hover with mouse over Storage Terminal - Jade still shows text "Logic Cable" instead of "Storage Terminal"
6. Hover with mouse over Item Importer - Jade still shows text "Logic Cable" instead of "Item Importer"

____

#### Versions:

- This mod: 1.1.11
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.68

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This mod does not have Jade integration.
See https://github.com/CyclopsMC/IntegratedDynamics/issues/1413
