### ISSUE TITLE
Extreme Reactors cannot properly store energy to battery (compatibility issue)

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedCrafting#116]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Probably, it's not ID bug, but ExtremeReactors bug, because ID works fine with similar power generation mod Solar Flux Reborn.
But I'm not sure. So here is link just for case:
https://github.com/ZeroNoRyouki/ExtremeReactors2/issues/180
If you will want to reproduce, then simplest reactor build is described in the "The Extreme Book" (Patchouli item) in the part "The Beginning / Your First Reactor"

#### Versions:

- This mod: 1.1.11
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.68

**Comment by uhloin** [comment]
Sorry for many bugs per day :)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
No wories, I'm always happy to see good bug reports for significant issues :-)

Let's put this one on hold until the mod authjor of Extreme Reactors replies.
