### ISSUE TITLE
energy autocrafting not working properly

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedCrafting#13]
#### Issue type:

- :bug: Bug

____

#### Short description:

crafting energy [e.g. generator] and crafting using energy [e.g. Thermal Expansion electric furnace] does not work.
#### Steps to reproduce the problem:

1. create a network with a storage interface, any generator, a battery, and any energy using machine [TE furnace]
2.connect each ones with a valid recipe [stick->2000rf: generator] [log+2000rf -> charcoal: furnace]

when the energy output recipe is selected, the item goes in as expected, but the energy received is not recognized by the crafter
when the item output recipe is selected, it will simply do nothing, even though the request is still trying to be processed (observed via terminal)
the exact same item output recipe but with the energy fed in via pipe instead of via recipe will work without issue

#### Expected behaviour:

crafting with energy as a product is impractical and is impossible as an ingredient
____

#### Versions:

- This mod: 1.0.1
- Minecraft: 1.12
- Forge: 14.23.5.2808

**Comment by rubensworks** [comment]
Does your generator auto-output its energy into the crafter? If not, then you may need an active energy importer pulling the energy out of the generator.

**Comment by antrobot1234** [comment]
The energy is automatically being pulled into the system’s battery, not the crafter.

**Comment by rubensworks** [comment]
This was actually a very stupid bug. Feel free to try out the latest dev build of IC.
