### ISSUE TITLE
Crafting job calculation packet overflow

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedCrafting#14]
#### Issue type:

- :bug: Bug

____

#### Short description:

i set up a system in the modpack (namely the enigmatica 2 expert mode modpack) to craft the advanced machine frame from IC2. whenever i request to craft it though, i get the issue

> java.lang.IllegalArgumentException: payload may not be larger than 32767 bytes

#### Steps to reproduce the problem:

1. run the enigmatica 2 expert mode pack with integrated crafting and terminals installed
2. create a system with all the recipes and machines required to craft the advanced machine frame from IC2

#### Expected behaviour:

the game should craft it as normal, as any of the prerequisites are craftable and the recipe is successfully caculated
____

#### Versions:

- This mod: 1.0.1
- Minecraft: 1.12
- Forge: 14.23.5.2781

#### Log file:
[pastebin file](https://pastebin.com/B7xQ1ahh)

**Comment by rubensworks** [comment]
Ah, that's an annoying one.

Note to self: implement a packet splitting algorithm similar to the one in Colossal Chests.
