### ISSUE TITLE
Consecutive crafting causing infinte loop?

### ISSUE THREAD

**Issue by darkshadow543** [CyclopsMC/IntegratedCrafting#2]
#### Issue type:

- :bug: Bug

____

#### Short description:
Attempting to set a craft writer to craft an object which has multiple levels of crafting causes the game to freeze.

#### Steps to reproduce the problem:
1. Set up a multi step crafting process, such as a chest.  In my case, I was trying to autocraft the crate from Actually additions.  All the perquisite materials were set up in the crafting interface.
2. Set a variable to the item that requires the multistep process.
3. Put the variable in a crafting writer.
4.  Enjoy the frozen game with a side of salty tears.

#### Expected behaviour:

____

#### Versions:

- This mod: 1.0.0
- Minecraft: 1.12.2
- Forge: 14.23.5.2807

#### Log file:

https://pastebin.com/te6vjBC5

https://pastebin.com/d45HnWDi

**Comment by darkshadow543** [comment]
It occasionally crashes when left in the crafting writer.  Just found that out.

**Comment by rubensworks** [comment]
The crash does not seem to be caused by an infinite loop, but due to a corrupted dependency graph. Will look into it.
