### ISSUE TITLE
version requirements

### ISSUE THREAD

**Issue by Staegrin** [CyclopsMC/IntegratedCrafting#21]
#### Issue type:

- :bug: Bug

____

#### Short description:

integrated crafting and integrated terminals versions 1.0.6 require integrated dynamics version 1.0.9 or above. version 1.0.8 is the only one available for download.

#### Expected behaviour:

after updating to version 1.0.6 for the game to start as normal or for a 1.0.9 version to be available.
____

**Comment by rubensworks** [comment]
Duplicate of https://github.com/CyclopsMC/CyclopsCore/issues/134
