### ISSUE TITLE
Allow crafting check to be disabled

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/IntegratedCrafting#23]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

If a recipe inside a crafting interface is invalid, a red cross will be shown.
It should be possible to completely disabled recipe validation in case mod integration would be bugged. A part setting should be sufficient for this.

**Comment by RGFTheCoder** [comment]
I had this issue trying to autocraft the energy cell recipe with a crafting table

**Comment by RGFTheCoder** [comment]
I also can't get recipes to work on the mechanical drying bin

**Comment by RGFTheCoder** [comment]
automating crafting for other blocks in this modseries is so complex compared to everything else; i find myself placing chests and hoppers all over the place because the mechanical blocks can't output to the pipes.
