### ISSUE TITLE
crafting ingredients being split into 64 and not showing that enough ingredients are available with integrated terminals

### ISSUE THREAD

**Issue by LordMZTE** [CyclopsMC/IntegratedCrafting#27]
#### Issue type:

- :bug: Bug

____

#### Short description:
when trying to craft planks out of logs with integrated terminals, it shows that there arent enough ingredients available even tho there clearaly are and also shows multiple stacks of the ingredient instead of adding them up
![grafik](https://user-images.githubusercontent.com/28735087/56817741-6dc2e780-6846-11e9-9427-ad4004ebef8e.png)

#### Steps to reproduce the problem:

1. Set up a storage system with a colossal chest as storage and add a crafting interface on a crafting bench
2. put in a lot of oak logs
3. program the interface to craft 4 oak planks out of 1 log using the logic programmer
4. request some planks so that there are more then 64 logs needed

#### Expected behaviour:

the planks all get craftet and the needed logs are displayed in 1 stack

____

#### Versions:

- This mod:  integrated dynamics: 1.12.2-1.0.11 integrated crafting: 1.12.2-1.0.6 integrated terminals: 1.12.2-1.0.6 integrated tunnels: 1.12.2-1.6.8 cyclops core: 1.12.2-1.1.1 common capabilities: 1.12.2-2.2.0
- Minecraft: 1.12.2
- Forge: 14.23.5.2831

**Comment by rubensworks** [comment]
Note to self: seems like a regression of https://github.com/CyclopsMC/IntegratedTerminals/issues/16

**Comment by Naosyth** [comment]
It looks like this is still happening when attaching an item interface to a Thermal Expansion cache. Only 64 items are recognized in the crafting plan
