### ISSUE TITLE
Fluid -> Item Recipes will use other fluids (and naturally halt crafting)

### ISSUE THREAD

**Issue by GreyMario** [CyclopsMC/IntegratedCrafting#28]
#### Issue type:

- :bug: Bug

____

#### Short description:

`Fluid -> Item` Recipe will take other fluids from the network even if they're the wrong fluid.
Observed using a *Mechanical Drying Basin* trying to craft *Block of Crystalized Menril* using *Lava* instead of *Liquid Menril*.

#### Steps to reproduce the problem:

1. Attach *Menril Resin* and *Lava* tanks to a network.
2. Create a *Menril Resin* -> *Block of Crystalized Menril* Recipe
3. Use it with a Mechanical Drying Basin to craft.

#### Expected behaviour:

Crafting using fluids should only ever accept that fluid.

____

#### Versions:

- Dynamics: `IntegratedDynamics-1.12.2-1.0.11`
- Tunnels: `IntegratedTunnels-1.12.2-1.6.8`
- Crafting: `IntegratedCrafting-1.12.2-1.0.6`
- Terminals: `IntegratedTerminals-1.12.2-1.0.6`
- Minecraft: `1.12.2`
- Forge: `14.23.5.2831`

**Comment by rubensworks** [comment]
This was apparently a quite recent bug caused by the LP in ID. (So you'll have to reconfigure your recipe variable after ID updates)
