### ISSUE TITLE
Mechanical Drying Basin does not accept Item, Fluid -> Item Recipe

### ISSUE THREAD

**Issue by GreyMario** [CyclopsMC/IntegratedCrafting#29]
#### Issue type:

- :bug: Bug

____

#### Short description:

The *Mechanical Drying Basin* does not accept a `Item, Fluid -> Item` Recipe correctly, such as *Menril Glass*. A Crafting Job Terminal will report that it's not accepted when the job is initiated, despite the Crafting Interface saying it's valid.

#### Steps to reproduce the problem:

1. Attempt to craft *Menril Glass* using Crafting components.

#### Expected behaviour:

*Menril Glass* should successfully craft.

____

#### Versions:

- Dynamics: `IntegratedDynamics-1.12.2-1.0.11`
- Tunnels: `IntegratedTunnels-1.12.2-1.6.8`
- Crafting: `IntegratedCrafting-1.12.2-1.0.6`
- Terminals: `IntegratedTerminals-1.12.2-1.0.6`
- Minecraft: `1.12.2`
- Forge: `14.23.5.2831`

**Comment by rubensworks** [comment]
Fixed in https://github.com/CyclopsMC/IntegratedDynamics/commit/fdff8c1eead9733756b46cc92813dd6975a3a70a
