### ISSUE TITLE
Filtered storage.

### ISSUE THREAD

**Issue by darkshadow543** [CyclopsMC/IntegratedCrafting#3]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:
A way to filter what goes into an inventory interface.  I would like it if I could dedicate chests to specific mods, so it would be a bit organized and not chaotic.  I also do not want to go into lasers, been there done that.  Also, I removed refined storage so I could try to have fun with integrated dynamics.  Time to push my computer to its limits.

**Comment by rubensworks** [comment]
Something like this has in fact been suggested a while ago: https://github.com/CyclopsMC/IntegratedTunnels/issues/98

But now that ITerms and ICrafting exist, this may require a boost in priority...

(Closing this in favor of https://github.com/CyclopsMC/IntegratedTunnels/issues/98, be sure to subscribe to the issue there)
