### ISSUE TITLE
Crafting Interface out of memory?

### ISSUE THREAD

**Issue by Shiruki** [CyclopsMC/IntegratedCrafting#32]
#### Issue type:

- :bug: Bug

____

#### Short description:

Unable to load game
#### Steps to reproduce the problem:

World has been very laggy, taking around 20-30 minutes for 1 minute to pass in game, but haven't found issue with that. Attempting to log into world is now giving attached crash, which seems to be related to Crafting Interface.
1. ...

#### Expected behaviour:

world load
____

#### Versions:

- This mod: IntegratedCrafting-1.12.2-1.0.7
- Minecraft: 1.12.2
- Forge: 14.23.5.2836

#### Log file:
https://pastebin.com/c6wp7t4H

**Comment by rubensworks** [comment]
Do you know what recipe was being processed at the time of the crash?

**Comment by Shiruki** [comment]
It might be crafting some Reinforced Drums from Extra utilities. In E2E so it's got multiple steps. But the I've been working in the world with extremely slow world ticks so i'm not completely sure if that's still crafting

**Comment by Shiruki** [comment]
I don't know if you need this, but I removed Crafting and Terminals and loaded the world. It's running smoothly at around 30 fps. Using Laggoggles I took a couple screen shots of the world. First one was before removing it and a picture after removing Crafting and Terminals. The only difference between them other than those two mods is 4 mekanism dymanic tanks that were removed while they were installed without impact. I can link the two pictures if you would like to see (or send the world as well)

**Comment by Shiruki** [comment]
Attempted to start with safe mode as suggested in #34, but gives same error

**Comment by rubensworks** [comment]
For reference, this was caused by a large amount of pending crafting jobs.
A (configurable) limitation for this will be available in the new version.
