### ISSUE TITLE
fatal crash on trying to add a **recipe** to a **list**

### ISSUE THREAD

**Issue by Yoghurt4C** [CyclopsMC/IntegratedCrafting#4]
- :bug: Bug

https://pastebin.com/SYfFgD1c
opened the programmer, selected "list" in the variable types, clicked on the "recipe" + from the list of things that can be added to a list and got the crash

IC 1.0.0
ID 1.0.0
forge 2807

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by rubensworks** [comment]
This will be fixed in the next ID release.

However, recipe editing inside lists is still a bit buggy due to https://github.com/CyclopsMC/IntegratedDynamics/issues/641, which will be fixed soon as well.
