### ISSUE TITLE
ore dict crafting just straight up isn't working

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedCrafting#40]
#### Issue type:

- :bug: Bug

____

#### Short description:
ore dictionary crafting is not working

#### Steps to reproduce the problem:
step one: try and make an ore dictionary crafting recipe
step two: try and use said recipe
step three: fail

#### Expected behaviour:

a functioning ore dictionary crafting
____

#### Versions:

- This mod: 1.0.9
- Minecraft: 1.12
- Forge: 8.0.99.99

**Comment by rubensworks** [comment]
Can you try to be a bit more specific in your steps to reproduce your problem? Because last oredict recipe I tried worked just fine.

**Comment by antrobot1234** [comment]
Well, for context, I've added IC to omnifactory as a replacement for logistic pipes and i was trying to craft a crafting table with gregtech wood planks (which are oredicted as wooden planks) with a recipe for anything that matches oak planks, but when i go to use the recipe, it says i'm missing oak planks.

**Comment by rubensworks** [comment]
Could you try without any other mods installed? I suspect (a mod in) your pack may be messing with oredict.

**Comment by antrobot1234** [comment]
it works in a standalone instance, but it's not working with gregtech items even though they fit the ore dictionary.

**Comment by rubensworks** [comment]
When you place your recipe in a display panel, do you see the gregtech items in the cycle?

**Comment by antrobot1234** [comment]
i see the circuit that it's asking for but doesn't exist, but it doesn't show any of the others

**Comment by rubensworks** [comment]
What circuit are you talking about? Some pictures may help.

**Comment by antrobot1234** [comment]
![image](https://user-images.githubusercontent.com/21179158/80224928-033ab800-8610-11ea-9995-e209a1a1496c.png)
that's the recipe (circuit on the bottom)

**Comment by rubensworks** [comment]
So if you visualize this recipe in the display panel, you correctly see this circuit passing by in the cycle?
And your storage system correctly contains this item?

What is the exact error you get when you try to start a crafting job? Can you share a screenshot of that?

**Comment by antrobot1234** [comment]
it's working this time for some reason, even though it wasn't cycling through with the exact same setup as before.

**Comment by antrobot1234** [comment]
also, side note, IC can look for items that are removed via crafttweaker

**Comment by rubensworks** [comment]
> it's working this time for some reason, even though it wasn't cycling through with the exact same setup as before.

Ok, thanks for checking. This can be closed then?

> also, side note, IC can look for items that are removed via crafttweaker

Not sure what you mean by this. But if you think this is a bug, please create a separate issue, as this is unrelated to this problem.

**Comment by antrobot1234** [comment]
actually, i realize what issue i was actually having. it's not that it's not recognizing the item when it's in the storage. it's not autocrafting the item via oredictionary when it's crafting recursively.

**Comment by antrobot1234** [comment]
actually, nevermind, false alarm
