### ISSUE TITLE
gregtech ore processing recipes cannot be marked as complete

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedCrafting#42]
#### Issue type:

- :bug: Bug

____

#### Short description:

any recipe with an output of crushed ore or impure dust (i'm not sure what else) from GregTech: Community Edition cannot function because the network does not recognize the item when it's inserted
#### Steps to reproduce the problem:

1. install GT:CE
2. make a recipe where an output is a crushed or (E.G. crushed iron ore) or impure dust (E.G. impure iron dust) in a dummy environment such as with a chest
3. the recipe will not recognize the completed recipe even when the item is manually inserted

#### Versions:

- This mod: 1.0.9
- GT:CE: 1.8.4.419
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

**Comment by rubensworks** [comment]
Do those items by any chance use special NBT tags or meta values?

**Comment by antrobot1234** [comment]
it uses damage values as with every other component item in gregtech, but it seems like crushed and impure ore specifically are the only ones to suffer this issue, while automating with other gregtech components work fine.

**Comment by rubensworks** [comment]
I just tried the exact same setup as you described with different GT:CE versions, and everything seems to be working properly on my end.

Please try again without any other mods installed. If you still experience the problem after that, please share a more detailed guide on how to reproduce the problem.
