### ISSUE TITLE
I can't craft multiple times

### ISSUE THREAD

**Issue by Sparkyure** [CyclopsMC/IntegratedCrafting#44]
when i try to craft something, it crafts once then tries to craft air (btw my english is not great so im sorry)
![2020-05-23_12 57 10](https://user-images.githubusercontent.com/65812163/82729087-eec40b00-9cf4-11ea-8aaf-5256313fcb03.png)

**Comment by rubensworks** [comment]
Can you share the steps required to reproduce this problem?

**Comment by Sparkyure** [comment]
I did everything you can read in these tutorials
![2020-05-23_17 19 08](https://user-images.githubusercontent.com/65812163/82734203-93584400-9d19-11ea-96c8-ea699648b576.png)
