### ISSUE TITLE
Mystical Agriculture Oak Wood Recipe Not Accepted

### ISSUE THREAD

**Issue by jmdev91** [CyclopsMC/IntegratedCrafting#46]
#### Issue type:

- :bug: Bug

____

#### Short description:

The Oak Wood recipe from Mystical Agriculture, which consists of three Wood Essences across the top of the crafting interface, is considered unacceptable by my crafting interfaces (which face regular crafting tables). All the other types of wood craft without issue, it's just Oak Wood that's a problem.

It's nothing inherent to Oak Wood in particular, as modifying the shape of the recipe via CraftTweaker allows it to work without issue. I suspect that because the resulting recipe is just a sequential list, the interface is assuming the recipe is supposed to be shapeless and is only searching for a match among that type of recipe.

#### Steps to reproduce the problem:

1. Create an Oak Wood recipe variable card using the Recipe type in the Logic Programmer based on the recipe added by Mystical Agriculture. Can be via JEI or by placing the items into the interface directly.
2. Place the recipe variable card into a crafting interface connected to a crafting table.
3. The recipe will not be considered acceptable.

#### Versions:

- This mod: 1.12.2-1.0.9
- Minecraft: 1.12.2
- Forge: 14.23.5.2854

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by jmdev91** [comment]
No problem. I've done some more testing and it turns out this is a problem for shapeless recipes and recipes which use vanilla ingredients as well. If you make a bread recipe card using the top row it'll be rejected by the crafting interface. Also made a CT recipe just to confirm it happens with recipes that use vanilla ingredients and it does. Hopefully that helps to narrow down the search a bit.
