### ISSUE TITLE
Seems autocrafting is not working properly

### ISSUE THREAD

**Issue by Consumerx54** [CyclopsMC/IntegratedCrafting#47]
#### Issue type:

- :question: Question 

____

#### Question:

I am using Integrated Dynamics for the first time and am now trying your integrated Crafting  v 1.12.2-10.10 in the mod pack FTB University.  I have set up the crafting exactly as explained in the in game tutorial and tried the example there to make planks from logs.  It made the planks once and will not make more.  Said in tutorial if I pull the planks out of the system it will make more but this does not happen it will never make more.  I didn't want to report this as a bug since this is my first time using this mod so it is probably me not a bug.  I put the recipe for planks in display screen and it shows proper recipe and have the item planks in crafting writer.. Any help or suggestions would be helpful  Great mod thankis

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Could you try this without any other mods installed?
