### ISSUE TITLE
Autocrafter stuck in: Calculating Crafting Plan 

### ISSUE THREAD

**Issue by Degani007** [CyclopsMC/IntegratedCrafting#5]
#### Issue type:

- :bug: Bug

____

#### Short description:
When having a multi-step crafting pattern with many crafting requirements. (for example the basic capacitor bank from Ender IO or solar gen from Mekanism etc.) the autocrafter will not do anything other than show "Calculating Crafting Plan." You can press escape and click it away but no crafting job will ever start.

#### Steps to reproduce the problem:

1. Setting up patterns: Ore -> Pulverize Ore -> Ingot
2. Setting up patterns to craft the item
3. Click on craft pattern and get the GUI with the "Calculating Crafting Plan"

#### Expected behaviour:

It should craft the pattern. If I make the sub-components (for example the basic capacitors, redstone block, 4 iron ingots) and make the requirement list shorter it will make the generator instantly.

____

#### Versions:

IntegratedCrafting-1.12.2-1.0.0
Minecraft 1.12
Forge1.12.2-14.23.5.2796

**Comment by darkshadow543** [comment]
I had this with my automation for AA crates

**Comment by rubensworks** [comment]
Does anything appear in your server console logs? It is possible that the plan calculation simply has failed.

**Comment by Degani007** [comment]
It is on a test single-player at this moment. Not certain how to provide these logs for you?

**Comment by rubensworks** [comment]
@Degani007 The `fml-client-latest.log` and `latest.log` should contain the information I need.

**Comment by Degani007** [comment]
Checked the log and found the error it gives when starting a crafting process that is too big.
See log for more info.
[latest.log](https://github.com/CyclopsMC/IntegratedCrafting/files/2784895/latest.log)

**Comment by rubensworks** [comment]
Thanks! That's exactly what I needed.

**Comment by rubensworks** [comment]
@darkshadow543 was right, this is the same problem as #2. Closing this in favor of that one.
