### ISSUE TITLE
Autocraft that requires items from a non-zero channel can't be request by output inteface.

### ISSUE THREAD

**Issue by shBLOCK** [CyclopsMC/IntegratedCrafting#51]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Autocraft that requires items from a non-zero channel can't be request by output inteface, but it works when manual request it using Integrated Terminals.

#### Versions:

- This mod: 1.0.10
- Minecraft: 1.16.4
- Forge: 35.1.13

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
What do you mean by "output interface"?

Can you give an example of a setup where you are experiencing your problem? Because I don't really understand the issue.

**Comment by shBLOCK** [comment]
Sorry, my english is not so good.

**Comment by shBLOCK** [comment]
I mean Item Exporter.

**Comment by shBLOCK** [comment]
![javaw_16V8436NBG](https://user-images.githubusercontent.com/50770712/103762981-25684f00-5054-11eb-8c25-626876f09aa9.png)
Want to autocraft this.
![javaw_vnyXiaGMaX](https://user-images.githubusercontent.com/50770712/103763102-5183d000-5054-11eb-8ea4-11eb59e5dcb0.png)
The redstone is in channel 1
![javaw_a7yM5bEdBU](https://user-images.githubusercontent.com/50770712/103763139-61031900-5054-11eb-8559-bc094e77d1a2.png)
I can manual request it.
![javaw_IcH5lhWnKQ](https://user-images.githubusercontent.com/50770712/103763175-724c2580-5054-11eb-814c-a5b4dc99ef56.png)
But can't request it by Item Exporter.

**Comment by rubensworks** [comment]
@shBLOCK Have you configured your item exporter to work on channel 1? (see its aspect settings)

**Comment by shBLOCK** [comment]
I tried, but it doesn't work.

**Comment by rubensworks** [comment]
Works fine for me.

Make sure your crafting interface, item interface, and item exporter share the same channel.

**Comment by shBLOCK** [comment]
Oh, found the issue, sorry for disturb.
