### ISSUE TITLE
When creating a crafting recipe and not putting the output in the top slot, crafting waits for air

### ISSUE THREAD

**Issue by 7eggert** [CyclopsMC/IntegratedCrafting#52]
#### Issue type:

- :bug: Bug 

____

#### Short description:
When creating a crafting recipe and not putting the output in the top slot, crafting waits for air

#### Steps to reproduce the problem:

1. take a pile of e.g. zinc dust and a zinc ingot.
2. Use the logic programmer to make a recipe variable
3. while doing this, use the third output slot
4. craft that ingot e.g. using the terminal

#### Expected behaviour:

One input generates one output; in my case it is put into a neighboring chest and then imported

(It's a thermal expansion machine; IC does not suck out the ingot by itself)

I changed the recipe to not include air; then it works.
____

#### Versions:

- This mod: IntegratedCrafting-1.16.4-1.0.10.jar
- Minecraft: 1.16.4
- Forge: 35.1.4

**Comment by rubensworks** [comment]
Thanks for reporting!
