### ISSUE TITLE
how exactly to trigger insert_recipe_planks advancement?

### ISSUE THREAD

**Issue by boneskull** [CyclopsMC/IntegratedCrafting#55]
#### Issue type:

- :question: Question 

____

#### Question:

Hi.  I'm following the "Setup Autocrafting" tutorial.  I've tried to create a Recipe like so:

![image](https://user-images.githubusercontent.com/924465/109440053-ace39600-79e5-11eb-8957-f4bedb058fa5.png)

I then insert the Variable into a Crafting Interface:

![image](https://user-images.githubusercontent.com/924465/109440083-d56b9000-79e5-11eb-98bd-e7e664bf59f2.png)

However, the advancement does not trigger:

![image](https://user-images.githubusercontent.com/924465/109440128-f207c800-79e5-11eb-8be1-e2427d79c163.png)

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
The input looks like a stripped log, instead of a normal log.

Also, could you try inserting the log into the very first slot?

**Comment by boneskull** [comment]
The input was pre-filled from JEI, so the icon rotates between the different “oak log” types (stripped, wood, etc). Maybe if I did it manually...

**Comment by boneskull** [comment]
Using the first slot and building the recipe manually seemed to work.  I cannot get JEI to prefill the recipe in the first slot; it's always copied into the center. 

Thanks!
