### ISSUE TITLE
Save last open terminal tab

### ISSUE THREAD

**Issue by 7eggert** [CyclopsMC/IntegratedCrafting#57]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

When you open a minecraft world, initially no terminal tab is pre-selected. It's a minor inconvenience to click on the desired tab but I reliably try to use it without first doing so.

https://youtu.be/j7sMwnNdvwY

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
This has been implemented in the latest update.
