### ISSUE TITLE
Extreme lag when taking items via terminal (sometimes to the point of crashing the game)

### ISSUE THREAD

**Issue by 7eggert** [CyclopsMC/IntegratedCrafting#58]
#### Issue type:

- :bug: Bug 

____

When taking things out of a terminal on a very filled network, the whole UI will lag. Taking the same things out of the player's inventory or the crafting grid is fine.

https://youtu.be/j7sMwnNdvwY

#### Steps to reproduce the problem:

1. Have a 6³ golden collossal chest with a lot of items.
2. Install an ID terminal.
3. Take something
4. The game lags until the item is put away

#### Expected behaviour:

No lag
____

#### Versions:

MC/Forge 1.16.5/36.0.42

AutoDropper-1.16.3-7.0.0.jar
Autofish-0.9.2-forge-mc1.16.4.jar
Basic-Nether-Ores-1.16.4.jar
Big-Buckets-1.16.4.jar
BowInfinityFix-1.16.4.jar
CapabilityProxy-1.16.5-2.1.9.jar
Chargers-1.16.4-3.0.2.4.jar
ChickenChunks-1.16.4-2.7.0.85-universal.jar
CodeChickenLib-1.16.4-3.5.0.401-universal.jar
ColossalChests-1.16.4-1.7.13.jar
CommonCapabilities-1.16.5-2.5.7.jar
CraftingCraft-1.16.4.jar
CyclopsCore-1.16.5-1.11.4.jar
EditSign-Forge-1.16.4-2.2.0.jar
EnderBags-1.16.4-6.3.1.jar
EnderStorage-1.16.4-2.7.0.161-universal.jar
EverlastingAbilities-1.16.5-1.7.1.jar
Excavator-1.8.2.jar
Flopper-1.16.4-1.0.6.jar
Futurepack-1.16.4-31.1.8176.jar
HarvestWithDispenser-3.0.1.jar
IntegratedCrafting-1.16.5-1.0.13.jar
IntegratedDynamics-1.16.5-1.6.1.jar
IntegratedTerminals-1.16.5-1.1.3.jar
IntegratedTunnels-1.16.5-1.7.0.jar
LargeFluidTank-16.1.6.jar
LavaClearView-1.16.2-1.1.0.jar
Mekanism-1.16.5-10.0.21.448.jar
MekanismAdditions-1.16.5-10.0.21.448.jar
MekanismGenerators-1.16.5-10.0.21.448.jar
MekanismTools-1.16.5-10.0.21.448.jar
NaturesCompass-1.16.5-1.8.6.jar
Placebo-1.16.4-4.4.1.jar
RepairChests-1.16.5-1.7.jar
ScalableCatsForce-2.13.4-build-2-with-library.jar
Simple-Magnets-1.16.4.jar
TipTheScales-1.16.5-3.0.0.11.jar
VillagersRespawn-1.16.5-1.36.0.3.jar
WorldEdit-CUI-FE3-1.16.5-3.0.9.jar
XaerosWorldMap_1.12.2_Forge_1.16.5.jar
Xaeros_Minimap_21.4.2_Forge_1.16.5.jar
advancedperipherals-0.3.6b.jar
ae2extras-1.3-1.16.5.jar
alwaysawitherskull_1.16.5-1.3.jar
appliedenergistics2-8.2.0.jar
architectury-1.9.136-forge.jar
backpacked-1.7.0-1.16.3.jar
backpacker-1.1.0-1.16.3.jar
branders-spawnermod-1.16.4-1.7.11.jar
cc-tweaked-1.16.4-1.95.2.jar
chiselsandbits-0.3.4-RELEASE.jar
cloth-config-4.11.15-forge.jar
cofh_core-1.16.4-1.2.1.jar
collective-1.16.5-2.24.jar
compact-crafting-1.0.0-alpha.2.jar
compactmachines-4.0.0-beta.2.jar
configured-0.2.0-1.16.3.jar
corpse-1.16.5-1.0.2.jar
custom-crosshair-mod-v1.1.0-forge-mc1.16.5.jar
diamondglass-1.16.5-4.2.27.jar
ezzoom-1.16.4-1.1.1.jar
ferritecore-2.0.3-forge.jar
fixedanvilrepaircost_1.16.5-1.4.jar
ftb-gui-library-1604.1.1.26.jar
furniture-7.0.0-pre19-1.16.3.jar
goprone-1.16.4-1.3.5.jar
infinitetrading_1.16.5-1.4.jar
invtweaks-1.16.4-1.0.1.jar
ironchest-1.16.4-11.2.10.jar
ironshulkerboxes-1.16.4-5.1.11.jar
itemcollectors-1.0.11-mc1.16.5.jar
jei-1.16.5-7.6.1.75.jar
kubejs-1605.3.6-build.176-forge.jar
kubejs-mekanism-1604.1.1.6.jar
kubejs-thermal-1605.1.1.6.jar
light-overlay-5.8.0.jar
mcjtylib-1.16-5.0.19.jar
mobcatcher-3.2.jar
nametagtweaks_1.16.5-1.5.jar
performant-1.16.2-4-3.30m.jar
preciseblockplacing-1.0.6+1.16.5.jar
preview_OptiFine_1.16.5_HD_U_G8_pre8.jar
proxies-0.17.0.jar
rftoolsbase-1.16-2.0.10.jar
rftoolsbuilder-1.16-3.0.16.jar
rftoolscontrol-1.16-4.0.8.jar
rftoolsdim-1.16-7.0.7-beta.jar
rftoolspower-1.16-3.0.8.jar
rftoolsstorage-1.16-2.0.11.jar
rftoolsutility-1.16-3.0.22.jar
rhino-1.7.13-build.14.jar
shutupexperimentalsettings-1.0.3.jar
tesseract-1.0.18-mc1.16.4.jar
theoneprobe-1.16-3.0.7.jar
thermal_cultivation-1.16.4-1.2.0.jar
thermal_expansion-1.16.4-1.2.0.jar
thermal_foundation-1.16.4-1.2.0.jar
thermal_innovation-1.16.4-1.2.0.jar
thermal_locomotion-1.16.4-1.2.0.jar
trashcans-1.0.8-mc1.16.4.jar
worldedit-mod-7.2.4.jar

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
You are not using the latest ITerms version. Please try again with the latest, and without any other mods installed.

**Comment by 7eggert** [comment]
This seems to happen if ores are processed quickly and there is a lot of storage. While debugging the other issue, I found that after the machines weren't there anymore, the item could be taken normally.

**Comment by rubensworks** [comment]
@7eggert Could you provide me with a reproducible world (without other mods installed), so I can debug this on my end?
