### ISSUE TITLE
Crash when making a recipe for 1 Coal = 36,000 RF

### ISSUE THREAD

**Issue by aaronhowser1** [CyclopsMC/IntegratedCrafting#60]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I made a recipe for 1 Coal = 36,000 RF in a Programmer block connected to a network

https://pastebin.com/3y0JUxNb

____

#### Versions:

- This mod: IntegratedCrafting-1.16.5-1.0.14
- Minecraft: 1.16.5
- Forge: 36.1.4

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by aaronhowser1** [comment]
Just tried it again, and while it doesn't crash, it isn't working how I expected.

![image](https://user-images.githubusercontent.com/15698722/116989827-e5c71200-ac97-11eb-80ed-b0c572305889.png)
This is the recipe in a Crafting Interface, it's aiming at a Coal Generator from RFTools.

![image](https://user-images.githubusercontent.com/15698722/116989868-f37c9780-ac97-11eb-92c5-56c1dab14e4f.png)
There's a Crafting Writer on the same network requesting 100k RF, so I would think it would try to craft some using Coal in the network.

I have some coal in a Chest that's in the network, which also has Planks that make a Chest any time it doesn't have one, just for testing, so I know that Chest definitely *is* in the network.

**Comment by aaronhowser1** [comment]
Also, is it intended that a single Crafting Writer can't have both the Craft Item *and* Craft Energy variables? When I try, it doesn't get a check and it drops on the ground when I leave the inventory. I had to place a second Writer for the energy.
