### ISSUE TITLE
MC 1.16.5 creating recipes with multiple input items: Can't change 

### ISSUE THREAD

**Issue by 7eggert** [CyclopsMC/IntegratedCrafting#63]
#### Issue type:

- :bug: Bug 
____

#### Steps to reproduce the problem:

When creating recipes with multiple input items, the amount of input items on the final recipe will be the stack size you clicked the slot with. You can change the number of input items in the GUI but when you take out the variable, it does use the unchanged value.

1. use whatever stack of items you have to create a recipe
2. adjust the numbers
3. take out the variable

Only the number of output items will be adjusted.

____

#### Versions:

- This mod: 
- Minecraft: 1.16.5
- Forge: 1.16.5-forge-36.1.2
- IntegratedCrafting-1.16.5-1.0.15.jar
- IntegratedDynamics-1.16.5-1.8.1.jar
- IntegratedREST-1.16.5-1.1.3.jar
- IntegratedTerminals-1.16.5-1.2.3.jar
- IntegratedTunnels-1.16.5-1.8.1.jar
- others

**Comment by rubensworks** [comment]
Thanks for reporting!
