### ISSUE TITLE
NullPointer when use jei to import a industrial foregoing‘s dissolution chamber's recipe

### ISSUE THREAD

**Issue by shBLOCK** [CyclopsMC/IntegratedCrafting#64]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. install industrial foregoing mod
2. create a recipe veriable by import a dissolution chamber's recipe from jei

#### Versions:

- This mod: 1.0.15
- Minecraft: 1.16.5
- Forge: 36.1.32

#### Log file:
https://pastebin.com/N1tm7GCg

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
It looks like industrial foregoing may be using an illegal `null` value for a certain fluid output (instead of `FluidStack.EMPTY`). Could you report this to their issue tracker, and link to this here?
