### ISSUE TITLE
Crafting Writer only craft the Recipe once

### ISSUE THREAD

**Issue by Charismara** [CyclopsMC/IntegratedCrafting#65]
#### Issue type:

- :bug: Bug 

____

#### Short description:
When using a crafting writer, it only crafts the job once and then it gets stuck. You need to cancel the job to craft another time and getting stuck again.

#### Steps to reproduce the problem:

1. Setup an autocrafting system
2. Insert required materials

#### Expected behaviour:
It should craft the recipe until there are no materials left

____

#### Versions:

- This mod: 1.0.10
- Minecraft: 1.12.2
- Forge: 14.23.5.2855

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm sorry, but MC 1.12 is not being maintained anymore.
