### ISSUE TITLE
Able to extract from crafting interface

### ISSUE THREAD

**Issue by Darkere** [CyclopsMC/IntegratedCrafting#66]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:

It is possible to extract from the crafting interface, causing major lag, as the extraction tool used will iterate over all slots in the system. 

See Original Issue for more details: https://github.com/NillerMedDild/Enigmatica6/issues/2810

#### Steps to reproduce the problem:

1. Setup integrated network.
2. Crafting with thermal expansion machine. 
3. set thermal expansion machine to auto extract (while easy to fix/avoid in this case, it presumably allows extractiong through pipes and similar)

____

#### Versions:

- This mod: IntegratedCrafting-1.16.5-1.0.16.jar
- Minecraft: 1.16.5
- Forge: 36.1.31

#### Profiler output:

https://spark.lucko.me/poYqgBcm5c

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Makes sense that this happens for large networks.

On the one hand I'm actually surprised that the crafting interface allows extraction by default, it probably should only allow insertion (at least by default).
