### ISSUE TITLE
Crafting jobs stuck, can only be cancelled manually

### ISSUE THREAD

**Issue by NoMoreStars** [CyclopsMC/IntegratedCrafting#67]
Apologies for the lackluster submission title, I'm no good with those
This was originally submitted to the Enigmatica 6 Github [here](https://github.com/NillerMedDild/Enigmatica6/issues/2824#issue-954106816)
I was asked to submit this bug here by the request of the modpack author.

#### Issue type:

- :bug: Bug 

____

#### Short description:

Autocrafting using Integrated Dynamics Integrated Crafting addon seems to be bugged and will frequently get stuck on simple one-stage crafting recipes that cannot be cancelled without manually cancelling them with the Crafting Job Terminal. I created a setup which simply autocrafts a single coal block and outputs it into a nearby chest. The inventory connected to the system containing the coal is a locked Storage Drawer filled with coal with the only other inventory connected to the system being an empty chest.

#### Steps to reproduce the problem:

1. Build a simple autocrafting setup complete with Crafting Job Terminal (make sure crafting writer has the "Ignore Storage Contents" boolean set to false)
2. Configure the setup so that items can be extracted from a single slot inventory (ie. Storage Drawer or Mekanism Bins) containing a large amount of coal on one end, and an empty inventory that items can be inserted into on the other end.
3. Configure the setup to autocraft coal extracted from the Drawer/Bin into coal blocks and output to the empty inventory on the other end
4. Open the chest and continue manually extracting coal blocks into the players inventory as they are crafted
5. Continue step 5 until coal blocks are no longer crafted
6. Open Crafting Job Terminal and cancel the requested craft
7. Open chest again to find a freshly crafted coal block
8. Repeat steps 4. to 7.

An example of the setup I used:
![2021-07-27_11 49 122](https://user-images.githubusercontent.com/38673759/127711572-ee9b036b-195d-4721-b78b-530c79259579.png)
![2021-07-27_12 01 272](https://user-images.githubusercontent.com/38673759/127711578-f39561db-d69a-4c5b-b7bc-65fcae280b33.png)

#### Expected behaviour:

Coal blocks should be continuously crafted as they are extracted.

____

#### Versions: 1.0.16

- This mod: Integrated Crafting
- Minecraft: 1.16.5
- Forge: 36.2.1
- Modpack: Enigmatica 6 0.5.6-0.5.8

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Sounds vaguely similar to #48, #11, but not quite.

@NoMoreStars Could you try reproducing without any other mods installed? So just a pure vanilla + ID setup, in order to rule out issues with other mods.

If you can build such a setup, could you send me the world?
That will help me out a lot when attempting to debug this issue in my dev environment.

**Comment by NoMoreStars** [comment]
Just ran a test as you requested and came out with the same results with a similar setup as seen above, just using a vanilla chest to extract coal this time.

Here's the setup:
[Integrated Crafting TEST.zip](https://github.com/CyclopsMC/IntegratedCrafting/files/6911469/Integrated.Crafting.TEST.zip)

**Comment by rubensworks** [comment]
Thanks! Will check soon.
