### ISSUE TITLE
Storage Terminal does not account for items in the crafting window when using JEI autofill

### ISSUE THREAD

**Issue by wrincewind** [CyclopsMC/IntegratedCrafting#69]
#### Issue type:

- :bug: Bug

____

#### Short description:

if you only have enough items to complete a craft by including items in the crafting grid, JEI will not recognise these items as available.

#### Steps to reproduce the problem:
for example:

1) have exactly 9 iron ingots. Put 4 of them in the crafting inventory, and 5 of them in the storage network.
2) open up JEI and try to craft an iron block
3) JEI will claim you have only 5 available ingots and ignore the ones currently in the crafting window.
4) attempting to complete the recipe despite the 'missing items' mouseover prompt from JEI will sometimes fill it in correctly and sometimes fail. 

i'd expect the system to treat the current contents of the crafting window as another inventory on the network, available for pulling from. 
____

#### Versions:

- This mod: integratedCrafting-1.16.5-1.0.17
- Minecraft: 1.16.5
- Forge: 36.2.2
- JEI: 7.7.1.118

**Comment by rubensworks** [comment]
Thanks for reporting!
