### ISSUE TITLE
[BUG]Crafting items through integrated crafting does not work. When trying to craft the following massages prevents it: "Missing storage ingredients"

### ISSUE THREAD

**Issue by MisterObvious25** [CyclopsMC/IntegratedCrafting#70]
#### Issue type:
:bug: Bug 
____

#### Short description:
Problem is similar to bug #56. Crafting Jobs cannot be started because it says items are not found on the network whilst there is plenty available when looking in the storage terminal.

#### Steps to reproduce the problem:
1. Create a new world
2. Create the network in the picture below
3. Add wood to the chest
4. All interface a on the same network number
5. Try to initiate a crafting job trough the terminal

World can be shared if necessary

#### Expected behaviour:

Crafting works succesfully
____
![2021-10-07_01 14 11](https://user-images.githubusercontent.com/19491809/136296178-8491fc61-af02-4380-9140-4f5af41a4622.png)
![2021-10-07_01 14 16](https://user-images.githubusercontent.com/19491809/136296182-67279a66-2090-4168-ac92-377e23c2c8a8.png)
![2021-10-07_01 14 20](https://user-images.githubusercontent.com/19491809/136296184-99ed422b-181b-4274-838e-249b6d95d386.png)
![2021-10-07_01 14 24](https://user-images.githubusercontent.com/19491809/136296186-0303f294-ad2f-4712-b43a-f76b7b0fbfe1.png)
![2021-10-07_01 14 25](https://user-images.githubusercontent.com/19491809/136296187-4059e106-41e3-4413-921b-66310bcf2354.png)
![2021-10-07_01 14 32](https://user-images.githubusercontent.com/19491809/136296188-b7e1d76e-dcb8-40e7-aede-2df207d6f253.png)

#### Versions:

CommonCapabilities-1.16.5-2.8.0.jar
CyclopsCore-1.16.5-1.11.10.jar
IntegratedCrafting-1.16.5-1.0.18.jar
IntegratedDynamics-1.16.5-1.10.2.jar
IntegratedTerminals-1.16.5-1.2.6.jar
IntegratedTunnels-1.16.5-1.8.6.jar
jei-1.16.5-7.7.1.122.jar

**Comment by SirGeremiah** [comment]
I've experienced the same behavior, with simple recipes (the only ones I've done so far) for planks, and crafting table.

**Comment by rubensworks** [comment]
How did you create the recipe exactly? Dies this occur for all recipes, or just for crafting tables?

**Comment by SirGeremiah** [comment]
I haven't had a recipe yet that works, but I've only created recipes that use a crafting table (piston, crafting table, oak planks). All give the same behavior MisterObvious reported. I can try something else, like a simple smelting recipe.

In my world, I should also note that the crafting table isn't vanilla - it's from FastWorkbench (though MisterObvious has experienced the same issue in another pack and in his Integrated-only test world, so I doubt the specific crafting table makes a difference.

**Comment by MisterObvious25** [comment]
> How did you create the recipe exactly? Dies this occur for all recipes, or just for crafting tables?

The recipe was created in a portable logic programmer. I also tried a Minecraft furnace recipe but this also does not seem to work.

**Comment by rubensworks** [comment]
> The recipe was created in a portable logic programmer.

Manually, or via JEI?

Are you also using FastWorkbench @MisterObvious25? If so, could you retry without any other mods installed?

**Comment by MisterObvious25** [comment]
@rubensworks 
I'm only using the mods listed in the bug report. The recipe was created with JEI. I am willing tot try it manually if you think this is the problem.

Not using FastWorkbench

**Edit:** just tried making the variable by putting in the items manually in the recipe grid, but gives the same result. Also tried using the normal logic programmer to no avail.

**Comment by paixz** [comment]
same issue here, from all the mods 6 1.8.5.

**Comment by rubensworks** [comment]
Fixed in Integrated Terminals 1.2.7. Should appear on CurseForge soon.
