### ISSUE TITLE
[1.16.5] When using the crafting writer, it ignores the "ignore storage contents" option and just keeps crafting

### ISSUE THREAD

**Issue by MisterObvious25** [CyclopsMC/IntegratedCrafting#72]
#### Issue type:
- :bug: Bug 

____

#### Short description:
Expected behavior is that when the crafting writer is used to craft a item(automatically), it will craft 1 recipe of the item and then stop until the items is no longer available in storage

#### Steps to reproduce the problem:

Steps and setup as in the video below 
https://user-images.githubusercontent.com/19491809/137587482-25fe9ed7-02ff-4523-b219-6905b4b5c32b.mp4

1. Create new world with mods below
2. Create setup as in video
3. Result

![2021-10-16_14 35 39](https://user-images.githubusercontent.com/19491809/137587691-6b07780d-72de-433e-b05d-19099368578c.png)
![2021-10-16_14 35 41](https://user-images.githubusercontent.com/19491809/137587694-a05d25ca-fe9d-4265-84b3-1d13339be293.png)
![2021-10-16_14 35 46](https://user-images.githubusercontent.com/19491809/137587696-4cecea16-feaa-4aa8-80be-cb49900c0002.png)
![2021-10-16_14 35 49](https://user-images.githubusercontent.com/19491809/137587698-25f505b6-dc70-48fd-b879-afcdaa527cd5.png)
![2021-10-16_14 35 53](https://user-images.githubusercontent.com/19491809/137587699-5468efc5-cb0f-4592-8082-ace4b0e74139.png)
![2021-10-16_14 35 59](https://user-images.githubusercontent.com/19491809/137587700-8d29b261-14e1-4857-84f9-d1bf7286645d.png)

#### Expected behaviour:

Expected behavior is a single craft of the item until the item is depleted in the system(network)
____

#### Versions:

Common Capabilities
kroeser
CommonCapabilities-1.16.5-2.8.0.jar

Cyclops Core
kroeser
CyclopsCore-1.16.5-1.11.10.jar

Integrated Crafting
kroeser
IntegratedCrafting-1.16.5-1.0.18.jar

Integrated Dynamics
kroeser
IntegratedDynamics-1.16.5-1.10.2.jar

Integrated Terminals
kroeser
IntegratedTerminals-1.16.5-1.2.7.jar

Integrated Tunnels
kroeser
IntegratedTunnels-1.16.5-1.8.6.jar

Just Enough Items (JEI)
mezz
jei-1.16.5-7.7.1.126.jar

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by MisterObvious25** [comment]
Published version works as intended. Thanks!!
