### ISSUE TITLE
Autocrafting basics

### ISSUE THREAD

**Issue by JosBouma** [CyclopsMC/IntegratedCrafting#73]
#### Issue type:

- :question: Question 

____

#### Question:
I'm trying to get autocrafting to work, but i seem to be missing something.

I've got a crafting interface, holding a recipe for oak planks.
The crafting interface is pointing towards a crafting table.

The recipe was made using the programmer with the recipe option.
Put an interface on a simple chest, with some logs.

When i try to craft the recipe from a storage terminal, it reports, invalid; missing storage ingredients, on both of the items/icons.

I can't seem to find any info on what i'n doing wrong and really would love to switch to autocrafting with ID/IC.

Thanks in advance,

Jos.

> Mod list:
buildinggadgets-1.16.5-3.8.0.jar
cofh_core-1.16.5-1.3.1.jar
CommonCapabilities-1.16.5-2.7.1.jar
Cucumber-1.16.4-4.1.10.jar
CyclopsCore-1.16.5-1.11.10.jar
ExtraStorage-1.16.5-1.5.0.jar
FluxNetworks-1.16.5-6.1.7.12.jar
ImmersiveEngineering-1.16.5-5.0.0-135.jar
IntegratedCrafting-1.16.5-1.0.17.jar
IntegratedDynamics-1.16.5-1.10.0.jar
IntegratedTerminals-1.16.5-1.2.5.jar
IntegratedTunnels-1.16.5-1.8.6.jar
jei-1.16.5-7.7.0.104.jar
journeymap-1.16.5-5.7.1.jar
Mantle-1.16.5-1.6.123.jar
mcjtylib-1.16-5.0.22.jar
Mekanism-1.16.5-10.0.21.448-all.jar
MouseTweaks-2.14-mc1.16.2.jar
MysticalAgriculture-1.16.4-4.1.8.jar
OreExcavation-1.8.157.jar
Patchouli-1.16.4-51.jar
ProjectE-1.16.5-PE1.0.1B.jar
refinedstorage-1.9.15.jar
rftoolsbase-1.16-2.0.11.jar
rftoolsbuilder-1.16-3.1.2.jar
rftoolspower-1.16-3.0.9.jar
rftoolsstorage-1.16-2.0.13.jar
rftoolsutility-1.16-3.1.2.jar
StorageDrawers-1.16.3-8.3.0.jar
TConstruct-1.16.5-3.1.2.265.jar
theoneprobe-1.16-3.1.4.jar
thermal_expansion-1.16.5-1.3.0.jar
thermal_foundation-1.16.5-1.3.2.jar
xnet-1.16-3.0.13.jar

![image](https://user-images.githubusercontent.com/36330229/138322066-fd2307d3-e2ab-4672-8470-7ba67b01fb61.png)
![image](https://user-images.githubusercontent.com/36330229/138320692-de5cc70e-76db-49ac-a135-a50c77757348.png)
![image](https://user-images.githubusercontent.com/36330229/138320563-22661381-3d39-471b-af7c-fb894a3507f2.png)
![id-ic](https://user-images.githubusercontent.com/36330229/138320040-878ba148-916e-46a8-b37e-b5abfea543ce.png)

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by MisterObvious25** [comment]
looks like the same issue as #70. Update integrated terminals, and the problem should be solved

**Comment by JosBouma** [comment]
Updating fixed it thanks!
