### ISSUE TITLE
Multiple batches crafted for indirect recipes

### ISSUE THREAD

**Issue by 7eggert** [CyclopsMC/IntegratedCrafting#75]
#### Issue type:

- :bug: Bug 

____

#### Short description:

1. If a recipe e.g. requires 2 glass
2. and if there is no glass nor sand
3. and my recipe for sand puts a stack of cobblestone into the grinders (two in a row, first one has the cafting interface)

then two stacks of cobblestone will be ground into two stacks of sand to smelt two glass

#### Expected behaviour:

Extra items from a recipe should be virtually put into storage so following recipes from walking the tree will use them.
____

#### Versions:

IntegratedCrafting-1.16.5-1.0.20.jar
IntegratedDynamics-1.16.5-1.10.6.jar
IntegratedREST-1.16.5-1.1.5.jar
IntegratedTerminals-1.16.5-1.2.11.jar
IntegratedTunnels-1.16.5-1.8.9.jar
forge-1.16.5-36.2.20-installer.jar

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I don't really understand the bug, could you clarify?

**Comment by 7eggert** [comment]
I have a recipe for a speed upgrade (Mekanism), it takes two glass.
I have a recipe for glass from sand
I have a recipe for 64 sand from 64 cobblestone because otherwise one of two machines is idle
I craft a speed upgrade
I have to wait for 128 sand to smelt two glass

**Comment by rubensworks** [comment]
Thanks, I think I understand the issue now.
It sounds like this may be related to #6. Ok if we close this issue here and merge it into #6?

**Comment by 7eggert** [comment]
It's maybe related by me trying a workaround and it wouldn't be necessary without, :-) but not really. 

Let me use all my artistic skills:

![untitled](https://user-images.githubusercontent.com/924567/147365227-aa707af2-1497-4b42-95cd-1d360f29ae27.png)

I'd expect 64 magenta items to be produced to make one blue item (and also for 8), but 128 (or 1024) would be produced.

**Comment by rubensworks** [comment]
Thanks, closing this in favor of #6.
