### ISSUE TITLE
Add a batch size to the crafting writer condition + the writer itself

### ISSUE THREAD

**Issue by Corfiot** [CyclopsMC/IntegratedCrafting#77]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

The crafting writer has the option to stop crafting if there is any amount of the crafted item in the network. This needs an actual number, so it checks how many and if less than the amount specified, it crafts.

Bonus points for adding a batch size to craft (without requiring recipes to be batched themselves), so it would see X items missing, and add a craft for X items once only.

Extra bonus points for making the batch size readable from a dynamic variable, so we could read what's empty in a buffer/chest and schedule the craft all at once.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Related to #6

Note to self: add batch property (a number, defaults to 1) to the crafting writer.

**Comment by rubensworks** [comment]
Will be added in the next update.
