### ISSUE TITLE
[1.18.1] Single Digit Qty Selection in Crafting Popup

### ISSUE THREAD

**Issue by enigmaquip** [CyclopsMC/IntegratedCrafting#80]
#### Issue type:

- :bug: Bug 

____

#### Short description:

![image](https://user-images.githubusercontent.com/6134440/155027976-72ad23ae-87af-44bc-8ec3-53ef31192464.png)
In the quantity selection screen, when trying to craft an item, the up/down arrows are unclickable and do not allow the user to add or decrease the amount by 1. The 10's/100's/1000's buttons all work as expected. The User is also not able to manually choose an amount if the 'textbox' is supposed to be editable.

#### Steps to reproduce the problem:

1. Create a recipe
2. Try to craft that recipe
3. Try to change the quantity crafted by 1

#### Expected behaviour:

____

#### Versions:

- Minecraft: 1.18.1
- Forge: 39.0.75
- CyclopsCore 1.18.1 - 1.13.0
- CommonCapabilities 1.18.1 - 2.8.2
- IntegratedDynamics 1.18.1 - 1.10.10
- IntegratedTunnels 1.18.1 - 1.8.11
- IntegratedTerminals 1.18.1 - 1.2.14
- IntegratedCrafting 1.18.1 - 1.0.21

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by enigmaquip** [comment]
Looks like this was handled already here https://github.com/CyclopsMC/IntegratedTerminals/pull/77
