### ISSUE TITLE
Batch crafting job gets stuck as soon as first item is crafted

### ISSUE THREAD

**Issue by mpavkovic** [CyclopsMC/IntegratedCrafting#83]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Batch crafting job will get stuck as soon as first item is crafted. After cancelling the job and requesting the same one all items are crafted without issue. After that all crafting jobs work fine until the world is reloaded or some time has passed.

#### Steps to reproduce the problem:

1. Create a new world (or load an existing one and skip to step 4)
2. Create a minimum setup consisting of Storage Terminal, Crafting Job Terminal, Crafting Table with an attached Crafting Interface, and a Chest (see screenshot for example)
3. Encode a Card with any recipe (for example, I used Scaffolding) and put it in Crafting Interface
4. Request multiple items to be crafted
5. Wait for crafting job to finish
6. Only first batch of items will be crafted and job will get stuck
7. Cancel job
8. Again, request multiple items to be crafted
9. All items are crafted and job is done

#### Expected behaviour:

Crafting multiples of same item should work without job getting stuck.

____

#### Versions:

- This mod: 1.0.21
- Minecraft: 1.16.5
- Forge: 36.2.34

Other mods installed:
- Common Capabilities v2.8.0
- Cyclops Core v1.12.3
- Integrated Dynamics v1.10.10
- Integrated Terminals v1.2.13
- Integrated Tunnels v1.8.9
- JEI v7.7.1.152

#### Screenshots

![2022-05-18_16 01 28](https://user-images.githubusercontent.com/803875/169064682-0945dfa6-fcb0-4220-b2f5-677733093409.png)

![2022-05-18_16 01 37](https://user-images.githubusercontent.com/803875/169064706-d2d6c02b-b897-4643-8423-a2103cac98dd.png)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Might be caused by febd15d7343b71c654d61b2574a126039ba2304b or [CyclopsMC/IntegratedDynamics#d631c69321896a4c0c634d782ba0cdcac39539e1](https://github.com/CyclopsMC/IntegratedDynamics/commit/d631c69321896a4c0c634d782ba0cdcac39539e1)
