### ISSUE TITLE
Crafting attempt is freezing the game

### ISSUE THREAD

**Issue by skupr** [CyclopsMC/IntegratedCrafting#84]
Modpack: FTB OceanBlock 1.12.0
Integrated Crafting Version: integratedcrafting-1.16.5-1.0.20.jar

During playing FTB OceanBlock, I've tried to set up autocrafting with Integrated Crafting. But if had frozen my game... Here's the scenario:
I've set up a simple Integrated Dynamics network with few chests + storage interfaces, crafting terminal, and crafting table + crafting interface connected to it.
![2022-05-23_17 13 17](https://user-images.githubusercontent.com/783636/169799433-78b30453-55a6-41e7-ab21-0d167f0c7c7d.png)

I've put recipes needed to autocraft "crafting terminal" ingredients.
![2022-05-23_17 13 22](https://user-images.githubusercontent.com/783636/169799440-7bdad4ca-c9d8-4c83-aaa7-659a08fb7074.png)

After that, I've opened storage terminal and tried to start crafting "crafting terminal" from it.
It displayed "Calculating crafting plan..." message and doing nothing more...
![2022-05-23_17 14 08](https://user-images.githubusercontent.com/783636/169799441-6b65647e-3308-4aaa-9d58-477a944510a7.png)

Moreover, after that, the world is kind of frozen - I can't interact with any machines, cannot open chests; even when I'm just looking at a chest or terminal, "one probe" says "Waiting for server..."
![2022-05-23_17 14 25](https://user-images.githubusercontent.com/783636/169799443-034c273b-e724-4e21-afb9-6b1f8e03dd1f.png)

I've tried to wait for a while (~10 minutes), but this hadn't been auto-repaired, so I had to kill MC and run it over.

I've also did a new world with a minimal crafting network and one simple recipe - and it did work!
Then I spent few tries to narrow down the problem - trying to disconnect/connect chests etc... It worked in a couple of times, but most  times the above problem happens... It takes a lot of time to debug this way - as it requires restarting Minecraft each time (I cannot even gracefully quit of the game into the main UI, it just saying "Saving world" forever...).

Here's also Forge log, unfortunately, it doesn't seem to reveal any difference...
[forge.log](https://github.com/CyclopsMC/IntegratedCrafting/files/8753761/forge.log)

Please tell me how can I help you debug this, which information may I collect etc...

**Comment by rubensworks** [comment]
Can you check if you're using the latest version of all integrated dynamics mods? Because this issue should've been fixed recently.
Also double-check if `craftingPlannerEnableMultithreading` in the integrated terminals config is set to `false`.

**Comment by skupr** [comment]
> Can you check if you're using the latest version of all integrated dynamics mods? Because this issue should've been fixed recently. Also double-check if `craftingPlannerEnableMultithreading` in the integrated terminals config is set to `false`.

Wow, thanks for fast reply!
`craftingPlannerEnableMultithreading` was set to true; I've changed it to false and crafting now works!
Thank you very much!
I'll report to the modpack authors that they should update their config.
