### ISSUE TITLE
[1.18.2] First use of Crafting Interface with plain crafting recipie always hangs job.

### ISSUE THREAD

**Issue by KirinDave** [CyclopsMC/IntegratedCrafting#85]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Upon loading a world in 1.18.2 (using either the Direwolf20 or ATM7 modpack, which is where I've reproduced this), crafting interfaces facing a crafting table (a plain recipe craft) always fail the first time they are used. In this case, failure means that the craft appears to hang, doing nothing.

After clearing this hung job with the Crafting Terminal, recipes in the interface craft normally.

I think this is a problem with Integrated Crafting (since this can also be triggered by crafting without the terminal) but I am unsure. Please let me know if I should refile this under the Integrated Terminals mod instead.

#### Steps to reproduce the problem:

1. Make an elementary InDy network with 1 chest, 1 crafting table, one storage terminal, a single recipe (vanilla crafting table is my test case), and a crafting terminal.
2. Log out/unload the world and rejoin.
3. Attempt to create 2+ crafting tables in the system via the Storage Terminal.
4. Observe the crafting tables do not appear. Observe the crafting job is stuck in the crafting terminal.
5. Cancel the crafting job in the crafting terminal.
6. Attempt to create 2+ crafting tables in the system via the Storage Terminal.
7. Observe that the crafting interface behaves normally.

#### Expected behaviour:

The first crafting job scheduled should complete as expected.
____

#### Versions:

- This mod: 1.0.22
- Minecraft: 1.18.2
- Forge:  40.1.25

On modpack use: I actually reported this to the ATM7 folks when I experienced it there and no one wanted to do the mod environment reduction process. I experienced this again in Direwolf20 (which uses very different mods, but the same version of your mod and has the same issue). I decided to report it despite this, as other people I've talked to have also noticed the issue in other mod envrionments.

Sorry if this breaks the rules a little, but I figured erring on the side of reporting is probably better than not doing so.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Please update to 1.0.23, this has already been fixed.
