### ISSUE TITLE
1.18.2 Autocrafting time out

### ISSUE THREAD

**Issue by iglee42** [CyclopsMC/IntegratedCrafting#86]
#### Issue type: 

- :bug: Bug 

____

#### Short description:

When you make more than one craft of the same type, such as crafting 8 planks, it kicks everyone and crashes the server

#### Steps to reproduce the problem:

1. Make autocrafting system
2. Make craft for planks (1 log = 4 planks)
3. Launch craft of 8 planks

#### Expected behaviour:

Just so that it crafts my planks and not crashes the server

____

#### Versions:

- This mod: 1.0.23
- Minecraft: 1.18.2
- Forge: 40.1.73

#### Log file:

None

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Can you provide some more details?

I would need to know first if you can reproduce this problem without any other mods installed.
