### ISSUE TITLE
The crafting writers "ignore storage contents" property seems to override "ignore crafting jobs"

### ISSUE THREAD

**Issue by elias098** [CyclopsMC/IntegratedCrafting#87]
#### Issue type:

- :bug: Bug 

____

#### Short description: 
If you enable the "ignore storage contents" it seems to act as if "ignore crafting jobs" is also enabled.

#### Steps to reproduce the problem:

i have to admit that i have not tested the following ingame due to having lost my account, but i have heard others say this and the code supports it
1. place a crafting writer on a network with recipes
2. set the writer to start one of the existing recipes
3. enable "ignore storage contents"
4. watch the crafting job list fill up

#### Expected behaviour:

I would expect the 2 properties to work independently of each other

the [code](https://github.com/CyclopsMC/IntegratedCrafting/blob/643747ee65c07dae347876b6ed4d7c20fc07975f/src/main/java/org/cyclops/integratedcrafting/part/aspect/CraftingAspectWriteBuilders.java#L156) for this interaction seems to be

```java
ignoreStorage
||
(
  !CraftingHelpers.hasStorageInstance(...)
  && 
  (
    ignoreCrafting || !CraftingHelpers.isCrafting(...)
  )
)
```

while i would expect it to be

```java
(
  ignoreStorage || !CraftingHelpers.hasStorageInstance(...)
)
&&
(
  ignoreCrafting || !CraftingHelpers.isCrafting(...)
)
```

____

#### Versions:

i know it says to not use just "latest" but looking at the code for this it affects all versions

**Comment by rubensworks** [comment]
Thanks for reporting!
