### ISSUE TITLE
Recipe Interface Terminal

### ISSUE THREAD

**Issue by Norcim133** [CyclopsMC/IntegratedCrafting#88]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

After I reach 50+ crafting interfaces on crafting tables, it becomes a big chore to track down and replace problematic recipes. It requires going to each crafting interface, one-by-one, to find the offending recipe.

AE2 solves this with an interface terminal that shows all crafting interfaces in the network, what block they are attached to and the recipe cards they contain. You can then insert and remove recipe cards for the entire network from this central location.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Would be more suitable for Intergrated Terminals, where this has been suggested before: https://github.com/CyclopsMC/IntegratedTerminals/issues/84
