### ISSUE TITLE
Modifying a recipe filled my JEI corrupts the registered recipe

### ISSUE THREAD

**Issue by MatthiasMann** [CyclopsMC/IntegratedCrafting#89]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When programming a recipe using the (portable) logic programmer and using JEI's + button to fill in the recipe and afterwards clicking on one of the ingredients does not only remove it from the new recipe you want to program on a variable card but also modifies the registered crafting machine (both crafting table and machines) corrupting the game season and needs a game restart to fix.

#### Steps to reproduce the problem:

1. Open the logic programmer
2. Select a crafting recipe
3. Use JEI to fill in a recipe with the + button
4. Left click on one of the crafting components (inputs)
5. Close the logic programmer
6. Check with JEI that the recipe is now modified

#### Expected behaviour:

The game wide recipe should not be changed

____

#### Versions:

- This mod: IntegratedCrafting-1.18.2-1.0.25
- Minecraft: 1.18.2
- Forge: 40.2.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you give an example of a (vanilla) recipe in which this occurs?

**Comment by MatthiasMann** [comment]
I was playing ATM7 to the sky mod pack - and I remember corrupting the following recipes:
Integrated Dynamic cable - by clicking on one of the sticks as I wanted to replace the tag based one with vanilla sticks,
Mekanism atomic alloy - by clicking on the reinforced alloy as I wanted to change the number

I think it also happened with a vanilla recipe - but I'm unsure which one it was.
It should work with a chest recipe as that also uses tags:
Fill in the chest recipe via JEI (should use tag planks) - then left click on of the planks in the recipe
