### ISSUE TITLE
Dedicated Storage Drawers support

### ISSUE THREAD

**Issue by Sar4h-3** [CyclopsMC/IntegratedCrafting#91]
#### Issue type:

- :bug: Bug 

____

#### Short description:
When using Storage Drawers connected to the system, the capacity calculation will add 1 max int to the capacity per drawer, completely ignoring their real size

#### Steps to reproduce the problem:

1. Build up a small storage system with at least one interface and terminal
2. Add a drawer to the interface. The drawer controller counts as a drawer too, even without attached drawers, but the displayed storage size won't change with attached drawers)

#### Expected behaviour:

The storage capacity is calculated the "right" way, adding the capacity for each drawer with the upgrades in mind

____

#### Versions:

- This mod: 1.19.2-1.1.0
- Minecraft: 1.19.2
- Forge: 43.1.5
- Storage Drawers: 1.19-11.1.2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This is not a bug, but merely a consequence of how Storage Drawers exposes its inventory to other mods.
Nothing we can do about that, aside from implementing dedicated support for this mod.
So I'm converting this to a feature request.

**Comment by rubensworks** [comment]
This should be resolved as of https://github.com/CyclopsMC/CommonCapabilities/commit/e328beaee24e12522308992e9ba9814e7cf53f08
