### ISSUE TITLE
Crash with reusable Mystical Agriculture infusion crystal

### ISSUE THREAD

**Issue by ChloeDawn** [CyclopsMC/IntegratedCrafting#94]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When auto-crafting tiered essence items from Mystical Agriculture with a Master Infusion Crystal, the game gets stuck in a crash loop.

#### Steps to reproduce the problem:

1. Setup a chest with an item interface, a crafting table with a crafting interface, and a chest with an item exporter.

    ![image](https://user-images.githubusercontent.com/9869940/233799553-28652051-8d1c-4a12-b8fb-10318ebcde96.png)

2. Configure an essence crafting recipe for the interface (4x previous tier + infusion crystal -> 1x next tier)
    - Ensure the Master Infusion Crystal is set to be Reusable
    
    ![image](https://user-images.githubusercontent.com/9869940/233799463-2aa64d99-3780-4a12-9318-a0507879447d.png)

3. Configure the item exporter to export the next tier of essence item, with Craft set to true

#### Expected behaviour:

The previous tier essence inserted into the input chest along with a Master Infusion Crystal to be auto-crafted into the next tier

____

#### Versions:

- This mod: 1.1.1
- Minecraft: 1.19.2
- Forge: 43.2.0
- CommonCapabilities: 2.9.0
- IntegratedDynamics: 1.16.4
- IntegratedTunnels: 1.8.18
- Mystical Agriculture: 6.0.8

#### Log file:

Reproduced in a clean minimal environment
https://mclo.gs/gFbqDmD

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
@ChloeDawn Could you share some more details for me to reproduce this problem? When does the crash occur *exactly*? If the chest(s) are empty? If there is one of the items missing (reusable or non-reusable)?

Note to self, the problem may be `inputInstance` somehow being `null` here: https://github.com/CyclopsMC
/IntegratedCrafting/blob/master-1.19/src/main/java/org/cyclops/integratedcrafting/core/CraftingHelpers.java#L1185

<blockquote><img src="https://avatars.githubusercontent.com/u/11808375?s=280&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC">Cyclops</a></strong></div><div>A collection of Minecraft mods that are mainly developed by @rubensworks - Cyclops</div></blockquote>
