### ISSUE TITLE
Productive bee's combs to block form doesn't work.

### ISSUE THREAD

**Issue by macCormack** [CyclopsMC/IntegratedCrafting#95]
#### Issue type: Trying to craft 4 blazing combs to a blazing comb block. 

- :question: Question 

____

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
There might be something non-standard going on with that recipe. Will depend on how it's implemented in that blazing comb block mod.
You can disable the crafting check flag on the crafting interface though, and it will try crafting the items anyways (but might fail if it's wrong after all).
