### ISSUE TITLE
Autocrafting with multiple manual Recipe gets stuck

### ISSUE THREAD

**Issue by MundM2007** [CyclopsMC/IntegratedCrafting#96]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Using multiple manual Crafters (e.g. RFTools Utility Crafters) to AutoCraft and using 3 recipes like this:
First Crafter: 1 Oak Log -> 4 Oak Planks
Second Crafter: 4 Oak Planks -> 1 Crafting Table
First Crafter: 1 Crafting Table (and other stuff) -> 1 Crafting Interface

Will get stuck and say "Waiting for other jobs to finish" for the crafting process of oak planks, after the first recipe has been crafted having blocking mode disabled in the same job 2 or more times (This also applies to all other recipes).
Yes, i know, this is really specific, but this probably also applies to all non crafting recipes, e.g.Smelting.
This is Just the setup that i found there are probably others aswell

#### Steps to reproduce the problem:

1. Setup to Crafters (from for example RFTools Utility), give them power, add the recipes and import out of them
3. place Crafting Interfaces against those and link up your importer, item interface and terminals
4. add the recipes to the crafting interfaces, so that they fit the Crafter
5. Add items to the network
6. Craft enough so that every subrecipe is crafted atlest 2 times
7. Try to craft again and see that it will output "Waiting for other jobs to finish"

Images
![image](https://github.com/CyclopsMC/IntegratedCrafting/assets/85188362/72f05011-6dc3-4a58-bbc1-eea06e243162)
![image](https://github.com/CyclopsMC/IntegratedCrafting/assets/85188362/8c1ff8d9-a9da-4a7f-85b9-bf06db095524)

#### Expected behaviour:

That it crafts the items

____

#### Versions:

- This mod: IntegratedCrafting-1.20.1-1.1.3
- Minecraft: 1.20.1
- Forge: 47.1.3

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by MundM2007** [comment]
After some more investigation this also applies to furnaces but only if the interfaces look directly at the furnace. Also there are obviously no other crafting jobs running.

**Comment by rubensworks** [comment]
I just tried this out, and was not able to reproduce this in a pure vanilla setup unfortunately.

> After some more investigation this also applies to furnaces but only if the interfaces look directly at the furnace. Also there are obviously no other crafting jobs running.

@MundM2007 Could you describe in detail what your setup is in this (including which recipes are configured, which items are in the storage, and how/when you start the crafting jobs)? If possible using only vanilla items and machines (such as the furnace).

**Comment by MundM2007** [comment]
This is difficult to replicate with only vanilla and integrated / tunnels / terminals / crafting, cause there aren't 3 furnace recipes that require the previous step. That's why i have added mystical agriculture and they have furnace recipes from cobbled soulstone to soul dust. Those are 3 recipes and those I've used. 
I've setup 3 furnaces with those recipes:
one from cobbled soulstone to soulstone, one from soulstone to smooth soulstone and one from smooth soulstone to soul dust.
Now you put cobbled soulstone in the network
**If blocking mode is disabled** and you request 2 or more soul dust and wait for the recipes to finish, this still works and request the same again it will not work and say:
![image](https://github.com/CyclopsMC/IntegratedCrafting/assets/85188362/c0e4e685-ff13-4c3d-a1c7-60bdeb5c4c82)
My setup (All importers have variable cards being in import all items, and there's an item interface to the chest):
![image](https://github.com/CyclopsMC/IntegratedCrafting/assets/85188362/61390c22-39c8-4d39-8fdd-ea984fd4d323)

**Comment by MundM2007** [comment]
this is actually stopping in the second furnace:
![image](https://github.com/CyclopsMC/IntegratedCrafting/assets/85188362/95c1c185-d8ea-4b37-b257-b962220b99ec)

**Comment by MundM2007** [comment]
If you have only one furnace with one recipe, this doesn't happen. But it's not allways possible to make all recipes in one. E.g. you have a recipe type similar to crafting table and there are two recipes you want to automate, but they take the same input and use a different shape / have one extra item. then there's no way to really automate both, because if you have one in another machine it would get stuck.

**Comment by MundM2007** [comment]
Sorry for commenting so much, but I'm also still finding the exact requirements for this really wierd bug to happen. This also seems to happen with 2 furnaces but only if the second recipe is in the one furnace and the other two in the other

**Comment by rubensworks** [comment]
Thanks for the additional info! I might be able to simulate that setup using some custom new recipes.

**Comment by rubensworks** [comment]
I just tried again with simulated furnace recipes (stone -> cobble -> sand -> glass), and was still not able to reproduce this problem unfortunately.
I suspect there are some things I'm still doing differently than you are.
Could you share a video with the precise steps you're following?

**Comment by MundM2007** [comment]
I also can't seem to replicate this with the new versions of all integrated mods from yesterday. It works now. If I donwgrade the version again it bugs again. Seems like whatever you've done has fixed this. I will open a new one if it occurs again.

**Comment by MundM2007** [comment]
btw. this isn't something you fixed by updating integratedCrafting, cause if you only downgrade that is also doesn occur

**Comment by MundM2007** [comment]
Ok, i have investigated again and is seems like your new integrated dynamics and cyclopsCore updates from yesterday make this really insconsistent. It still sometimes happens, but i can't make a exact step by step tutorial, on how to replicate. So if you want you can close this issue, as it seems mostly fixed. And if I ever find something new about this i'll open a new one and let you know.

**Comment by rubensworks** [comment]
Ok, that sounds like a good plan!
To anyone else reading this, be sure to comment on this issue if you're encountering this issue and are able to reproduce this consistently (preferably using only vanilla+ID).

Thanks for checking!
