### ISSUE TITLE
Autocrafting gets stuck if the crafted item is moved. 

### ISSUE THREAD

**Issue by derram** [CyclopsMC/IntegratedCrafting#98]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Tested here with a barebones setup of Integrated Dynamics/Crafting/Terminals/Tunnels, Common Capabilities, and Cyclops Core.

Autocrafting continues if output remains in a storage container, thinks the output is missing if the item is moved. 

#### Steps to reproduce the problem:

A setup for crafting granite, no hopper under output (interface on right has highest priority):
![2023-09-01_03 51 51](https://github.com/CyclopsMC/IntegratedCrafting/assets/5730335/1effeee7-5b17-486f-a786-ced5b4439d5c)

Crafting proceeds as expected. 
![2023-09-01_03 51 41](https://github.com/CyclopsMC/IntegratedCrafting/assets/5730335/73cb2c3d-b656-4d9e-9f3c-402b0ea38570)

Add hopper below output chest.

![2023-09-01_03 52 08](https://github.com/CyclopsMC/IntegratedCrafting/assets/5730335/af78a738-0284-4214-b562-8c79e028f8e0)

Crafting grinds to a halt.

![2023-09-01_03 52 02](https://github.com/CyclopsMC/IntegratedCrafting/assets/5730335/5a88a3e1-7a35-4605-b7b3-bce5a92ad348)

This also happened to me in a modpack when I used a filtered interface to put the output directly into a machine. In that case it was a Create Millstone. 

#### Expected behaviour:

Autocrafting should be able to tell when it's put the crafted item away. 

____

#### Versions:

![2023-09-01_04-06](https://github.com/CyclopsMC/IntegratedCrafting/assets/5730335/c901b5fc-69b3-480c-b507-26c2d99ba338)

![2023-09-01_04-07](https://github.com/CyclopsMC/IntegratedCrafting/assets/5730335/248e9a71-59d3-446e-a482-8230e16b4598)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Note to self: similar to an issue with crafting item exporter. There, we added a forced index reload once the crafting job is done. We need something like that here as well, to make sure we add the crafted item to the index so it's marked as "completed" before the hopper pulls it out again.

**Comment by derram** [comment]
Note the bit I said about the filtered interface. 

I was hoping to skirt around the problem by having ID handle the entire process, all on the same network, and it still lost track of the output.

**Comment by derram** [comment]
Did a bit more testing, and yeah using a filtered interface on the hopper causes the same problem.

![2023-09-01_04 30 41](https://github.com/CyclopsMC/IntegratedCrafting/assets/5730335/ca9d0e3f-720e-4a32-94f6-90234e02b1cf)

![2023-09-01_04 30 44](https://github.com/CyclopsMC/IntegratedCrafting/assets/5730335/22bd57b5-40b8-432e-8bc6-1e02bcb7d532)

**Comment by rubensworks** [comment]
A temporary workaround would be to replace the hopper with an ID exporter that is attached to the main network.

**Comment by derram** [comment]
Went back to the pack to implement the change, and I can't tell if I'm hitting the same bug while using the exporter or a similar but different bug.

In the pack I am crafting cobble + quartz to diorite and then diorite and quartz to granite. I think it might be getting stuck on the diorite side of things which doesn't send anything out of the network. 

That's just a crafting interface and interfaces on the storage containers, and then the crafting interface for granite pulls from the output from the diorite crafter.

**Comment by derram** [comment]
Yeah, did some more testing in the barebones install, and the crafting chugs along fine for a bit, but then gets stuck more than likely because of the diorite crafting.  There's an exporter attached to the back side of that barrel on the bottom right. 

![2023-09-01_05 58 53](https://github.com/CyclopsMC/IntegratedCrafting/assets/5730335/5b4d448a-8095-4852-b54d-64d41063f7dd)
