### ISSUE TITLE
Updating network restart Crafting jobs

### ISSUE THREAD

**Issue by ZeekDaGeek** [CyclopsMC/IntegratedCrafting#99]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Updating an Integrated Dynamics network causes crafting jobs to restart. Not much a problem with small dedicated crafting tasks, but if you have a large network responsible for your storage, autocrafting, etc. Your network updates frequently and throws off any current crafting.

#### Steps to reproduce the problem:

Create a system would allow extra input to make crafting fail, Powah is a good option.

1. Starting set up:
![image](https://github.com/CyclopsMC/IntegratedCrafting/assets/1709288/e647d01e-2750-41d8-a821-6f1024119133)
2. Add a cable / Remove a cable.
3. 👀
![image](https://github.com/CyclopsMC/IntegratedCrafting/assets/1709288/d97588b9-37b7-4bb4-852a-8f369ab1d5b9)

#### Expected behaviour:

____

#### Versions:

- This mod: 1.8.21
- Minecraft: 1.19.2
- Forge: 43.2.14

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
@ZeekDaGeek Unfortunately, I'm unable to reproduce your problem (with a vanilla furnace setup). Could you give some more details on how you are triggering the crafting jobs exactly. I see a crafting writer in your screenshot, but I'd like to know what aspect is active, and what its settings are.

**Comment by ZeekDaGeek** [comment]
The Crafting Writer is set to Craft Item -> Variable Cart set to Item: Uraninite. The only changed setting is "Ignore Storage Contents" = true, with the intent of the system to always craft any Uranium in the system into Uraninite.

I attempted to make it simpler to see if it's related to the machine:

![image](https://github.com/CyclopsMC/IntegratedCrafting/assets/1709288/7fd15abf-83aa-45f2-8ca7-14abe59048cf)

Any time I place down a new cable on the ID Network an additional Uranium gets exported by the Crafting Interface into the chest, and the Duration in the Crafting Job terminal gets set back to 0:00:00, which I take to mean that it restarted the existing crafting job.

If I take out the Variable Card from the Crafting Writer so no new jobs are being requested and then destroy a cable in the network the job gets canceled.

**Comment by rubensworks** [comment]
Thanks for the additional info. I managed to reproduce the problem now. Now for debugging it...
